//! 2026-06-23-005 F1 (R9 BLOCKER): `#[non_exhaustive]` enforcement
//! fixture.
//!
//! This file is expected to FAIL to compile. It matches a
//! `RejectionKind` value (which is `#[non_exhaustive]`) without
//! a `_ =>` fallback arm; the Rust compiler MUST reject it with
//! "non-exhaustive patterns" because the surrounding function
//! returns a unit type — the match must cover all *known* variants,
//! and `#[non_exhaustive]` requires the wildcard fallback.
//!
//! The companion `tests/ui/non_exhaustive_match.stderr` (auto-
//! generated by `trybuild`) records the expected diagnostic so
//! future drift is caught by `cargo test -p ralph-core --test trybuild`.
//!
//! Note: we intentionally match on `RejectionKind` directly (not on
//! the return value of `CoordinatorDispatcher::dispatch`). The
//! `RejectionKind` `#[non_exhaustive]` attribute is what makes
//! this test case a compile error — matching the function return
//! type would only test `CoordinatorAction`'s exhaustiveness, which
//! is a separate (and currently non-`#[non_exhaustive]`) enum.
//!
//! Reference: `docs/plans/2026-06-23-005-fix-ce-executor-serial-hard-gate-half-edge-recovery-plan.md` R9.

use ralph_core::preset::engine::gates::RejectionKind;

#[allow(dead_code)]
fn _exhaustive_match(k: RejectionKind) -> &'static str {
    match k {
        RejectionKind::MissingField => "missing_field",
        // No `_ =>` fallback and no exhaustive list of all
        // 12 known variants → compile error: "non-exhaustive
        // patterns: `HandoffArtifact`, `HandoffFilenameMismatch`,
        // ... not covered".
        //
        // Removing the `// No _ =>` comment block (or listing every
        // variant explicitly) restores compilation; the `trybuild`
        // test passes only if THIS file fails with the expected
        // non-exhaustive error.
        RejectionKind::TopicOwnership => "topic_ownership",
    }
}

// `trybuild` compiles each `tests/ui/*.rs` as a binary crate, so a
// `main` function is required even when the failure we want to
// catch is in a non-`main` function above. The function body
// itself is dead code; the diagnostic is emitted at the
// `match` site.
#[allow(dead_code)]
fn main() {
    let _ = _exhaustive_match(RejectionKind::MissingField);
}
