//! 2026-07-02-006 plan U7: `on_test_passed_step` primitive.
//!
//! Pure decision over `test.passed` (the only topic that
//! drives unit-loop → review / fix-unit → plan-end
//! transitions). The primitive consumes an in-memory
//! `StepProgressFixture` and the transition's `on:` payload
//! (`{primitive: on_test_passed_step, step_kind, when}`) and
//! returns the target phase id when the rule matches.
//!
//! **No I/O.** The fixture is built by the test or by the
//! runtime's `StepProgressObserver`; U21 adds the parser that
//! builds one from a `test.passed` payload.

use serde::{Deserialize, Serialize};
use serde_yaml::Value;

/// Step kind the rule discriminates on. The fixture carries
/// the runtime's classification of the step that just passed.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum StepKind {
    /// `unit_loop` plan unit (i.e. one of the original plan's
    /// implementation units, not a fix-unit).
    PlanUnit,
    /// `fix_units` plan unit — the step was generated by a
    /// `review.complete.verdict=pass_with_residuals+fix_plan`
    /// or `verdict=fail+fix_plan` chain.
    FixUnit,
}

impl StepKind {
    pub fn from_token(token: &str) -> Option<Self> {
        match token {
            "plan_unit" => Some(Self::PlanUnit),
            "fix_unit" => Some(Self::FixUnit),
            _ => None,
        }
    }
}

/// In-memory step progress fixture (U7). U21 builds one from
/// `test.passed` payloads; U27 builds one for
/// `advance_step_on_test_passed`. The struct is intentionally
/// trivial — the primitive does not read from disk.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct StepProgressFixture {
    pub kind: StepKind,
    /// 1-based step index. Combined with the plan's
    /// `step_count`, the primitive can compute "last step".
    pub index: u32,
    /// Total number of steps in the plan (or fix batch). The
    /// runtime injects this when the fixture is built.
    pub total: u32,
}

impl StepProgressFixture {
    /// `true` when this step is the last of its batch.
    pub fn is_last(&self) -> bool {
        self.total > 0 && self.index >= self.total
    }
}

/// Pure decision: return `Some(target_phase)` when the trigger
/// matches the fixture and the topic is `test.passed`.
///
/// The trigger encodes:
///
/// ```yaml
/// on:
///   primitive: on_test_passed_step
///   step_kind: plan_unit | fix_unit
///   when: last | always
/// ```
pub fn evaluate(
    trigger: &Value,
    event_topic: &str,
    fixture: &StepProgressFixture,
) -> Option<String> {
    if event_topic != "test.passed" {
        return None;
    }

    let mapping = trigger.as_mapping()?;
    let primitive = mapping
        .get(Value::String("primitive".to_string()))?
        .as_str()?;
    if primitive != "on_test_passed_step" {
        return None;
    }

    let step_kind = mapping
        .get(Value::String("step_kind".to_string()))?
        .as_str()
        .and_then(StepKind::from_token)?;
    if step_kind != fixture.kind {
        return None;
    }

    let when = mapping
        .get(Value::String("when".to_string()))
        .and_then(|v| v.as_str())
        .unwrap_or("always");

    let matched = match when {
        "last" => fixture.is_last(),
        "always" => true,
        _ => false,
    };

    if matched {
        // The target phase id is encoded in the surrounding
        // transition rule (`to: ...`). U10's `TransitionEvaluator`
        // looks that up; U7 only returns a hit signal.
        Some(when.to_string())
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn last_fix_unit_matches() {
        let trigger: Value = serde_yaml::from_str(
            r"
primitive: on_test_passed_step
step_kind: fix_unit
when: last
",
        )
        .unwrap();
        let fixture = StepProgressFixture {
            kind: StepKind::FixUnit,
            index: 2,
            total: 2,
        };
        assert_eq!(
            evaluate(&trigger, "test.passed", &fixture),
            Some("last".to_string())
        );
    }

    #[test]
    fn last_plan_unit_matches() {
        let trigger: Value = serde_yaml::from_str(
            r"
primitive: on_test_passed_step
step_kind: plan_unit
when: last
",
        )
        .unwrap();
        let fixture = StepProgressFixture {
            kind: StepKind::PlanUnit,
            index: 8,
            total: 8,
        };
        assert_eq!(
            evaluate(&trigger, "test.passed", &fixture),
            Some("last".to_string())
        );
    }

    #[test]
    fn non_last_plan_unit_does_not_match_last_trigger() {
        let trigger: Value = serde_yaml::from_str(
            r"
primitive: on_test_passed_step
step_kind: plan_unit
when: last
",
        )
        .unwrap();
        let fixture = StepProgressFixture {
            kind: StepKind::PlanUnit,
            index: 4,
            total: 8,
        };
        assert_eq!(evaluate(&trigger, "test.passed", &fixture), None);
    }

    #[test]
    fn work_done_does_not_match() {
        let trigger: Value = serde_yaml::from_str(
            r"
primitive: on_test_passed_step
step_kind: plan_unit
when: last
",
        )
        .unwrap();
        let fixture = StepProgressFixture {
            kind: StepKind::PlanUnit,
            index: 8,
            total: 8,
        };
        assert_eq!(evaluate(&trigger, "work.done", &fixture), None);
    }

    #[test]
    fn mismatched_step_kind_does_not_match() {
        let trigger: Value = serde_yaml::from_str(
            r"
primitive: on_test_passed_step
step_kind: plan_unit
when: last
",
        )
        .unwrap();
        let fixture = StepProgressFixture {
            kind: StepKind::FixUnit,
            index: 1,
            total: 1,
        };
        assert_eq!(evaluate(&trigger, "test.passed", &fixture), None);
    }

    #[test]
    fn always_trigger_matches_any_step() {
        let trigger: Value = serde_yaml::from_str(
            r"
primitive: on_test_passed_step
step_kind: plan_unit
when: always
",
        )
        .unwrap();
        let fixture = StepProgressFixture {
            kind: StepKind::PlanUnit,
            index: 1,
            total: 8,
        };
        assert_eq!(
            evaluate(&trigger, "test.passed", &fixture),
            Some("always".to_string())
        );
    }
}
