//! Task ledger projection.
//!
//! Plan ref: U2 of
//! `docs/plans/2026-06-17-003-hat-orchestrator-state-projection-phase1-plan.md`.
//!
//! These two helpers write `.ralph/agent/tasks.jsonl` from the
//! projector. The projector is the **sole** writer in Phase 1
//! (preset instructions ban the agent from calling
//! `ralph tools task ensure|start|close|fail`).
//!
//! Failures bubble up as `Err(reason)`; the caller converts them
//! into a [`super::Rejection`] and the bus emits
//! `event.state_projection.rejected`.

/// Canonical owner hat id assigned to projector-materialised rows.
///
/// Every row written by `project_ensure_task` /
/// `project_ensure_task_batch` carries this `owner_hat_id` so the
/// close-before-done ACL succeeds when the executor's `exec.unit.done`
/// hits `TaskStore::close`. Fix-units keep coordinator ownership (minted
/// via `ralph tools task ensure --for-fix-unit`) and exempt this
/// default. Centralising the constant keeps the two projection paths
/// (`project_ensure_task` + `project_ensure_task_batch`) in lock-step
/// — if a future hat acquires executor-equivalent ownership, change
/// this constant rather than the per-call site.
pub(crate) const PLAN_UNIT_OWNER_HAT: &str = "executor";

// This module **owns** the deprecated `tasks_cache` mirror:
// `persist` updates it as a write-through of the on-disk ledger.
// The mirror is kept in sync with the canonical
// `LedgerSnapshot` (via `sync_to_ledger_snapshot` and
// `project_ledger_snapshot`) so legacy callers continue to
// observe the same view, while the U2 path reads from the
// snapshot directly. Touching the field here is therefore
// intentional and unavoidable.
#[allow(deprecated)]
use std::collections::{HashMap, HashSet};
use std::path::Path;

use serde_json::Value;

use crate::state_projector::ProjectionContext;
use crate::state_projector::json_pointer;
use crate::task::Task;
use crate::task_store::{TaskStore, is_fix_unit_id, is_fix_unit_key};

/// Validate that a user-supplied `task_id` follows one of the
/// canonical formats. We accept two shapes:
///   1. `task-{unix_timestamp}-{4_hex_chars}` — generated by
///      `Task::generate_id` for ordinary runtime tasks.
///   2. `task-{plan_slug}-fix{NN}u{NN}-{ts_hex}` — generated by
///      `Task::fix_unit_task_id` for ce-executor fix-units.
/// Anything else (e.g. `task-1782813211-u2`) is rejected at the
/// projection boundary so the coordinator prompt template is forced
/// to mint a fresh, correctly-formatted id per unit.
///
/// IMPORTANT: This validator is **only** applied when the payload
/// carries a fix-unit shaped `task_key` (`ce-executor:{plan}:fix-NN:...`).
/// Ordinary runtime tasks and non-ce-executor presets are intentionally
/// not held to this strict format so that legacy ids, human-CLI ids,
/// and other presets continue to work.
fn is_valid_task_id_format(task_id: &str) -> bool {
    if task_id.is_empty() || !task_id.starts_with("task-") {
        return false;
    }
    static FIX_UNIT_RE: std::sync::OnceLock<regex::Regex> = std::sync::OnceLock::new();
    let fix_re = FIX_UNIT_RE.get_or_init(|| {
        regex::Regex::new(r"^task-[a-z0-9_]*-fix\d{2}u\d{2}-[0-9a-fA-F]+$").unwrap()
    });
    // Shape 1: ordinary runtime id.
    if let Some(rest) = task_id.strip_prefix("task-") {
        let parts: Vec<&str> = rest.splitn(2, '-').collect();
        if parts.len() == 2
            && !parts[0].is_empty()
            && parts[0].chars().all(|c| c.is_ascii_digit())
            && parts[1].len() == 4
            && parts[1].chars().all(|c| c.is_ascii_hexdigit())
        {
            // 2026-07-01-001 plan U4 (primary-20260630-175407
            // P0-3): shape-1 ids embed a unix timestamp in
            // `parts[0]`. The legacy validator accepted any
            // digit string — the fixture in
            // `primary-20260630-175407` shows the coordinator
            // hand-wrote `task-1751414400-a1b2` (2025-07-01)
            // for `fix-02`, which the format check passed.
            // Reject timestamps outside the loop window so
            // stale hand-written ids can no longer poison the
            // task ledger. The window is
            // `[now - 6 months, now + 60s]`; 6 months is wide
            // enough to accept any current-loop fixtures and
            // snapshots while still rejecting the year-old
            // `1751414400` (2025-07-01) timestamp in the
            // 175407 fixture. The forward 60s tolerance covers
            // normal clock skew.
            return is_valid_task_id_timestamp(parts[0]);
        }
    }
    // Shape 2: fix-unit id.
    if fix_re.is_match(task_id) {
        // 2026-07-01-001 plan U4: shape-2 ids embed a hex
        // timestamp as the trailing segment. Apply the same
        // window check (the helper computes the seconds and
        // falls back to accept-on-parse-failure so we do not
        // break ids from older runs whose hex segment is not a
        // valid unix_ts).
        let ts_hex = task_id.rsplit('-').next().unwrap_or("");
        return is_valid_task_id_hex_timestamp(ts_hex);
    }
    false
}

/// 2026-07-01-001 plan U4: window-check the unix timestamp
/// embedded in a shape-1 `task-{ts}-{4hex}` id. The window is
/// `[now - 6 months, now + 60s]`. Returns `true` when
/// `now_unix_ts` is `None` so legacy callers without a clock
/// continue to accept shape-1 ids (the format check itself
/// already ran).
fn is_valid_task_id_timestamp(ts_str: &str) -> bool {
    let Ok(ts) = ts_str.parse::<i64>() else {
        return false;
    };
    let Some(now) = current_unix_ts() else {
        return true;
    };
    let six_months = SIXTY_SECONDS * 60 * 24 * 365 / 2;
    let lower = now.saturating_sub(six_months);
    let upper = now.saturating_add(SIXTY_SECONDS);
    ts >= lower && ts <= upper
}

/// 2026-07-01-001 plan U4: window-check the hex timestamp
/// embedded in a shape-2 `task-...-fix{NN}u{NN}-{ts_hex}` id.
/// The helper is permissive on parse failure — old fixtures
/// may carry non-time hex values that we still want to accept
/// so existing snapshots do not regress.
fn is_valid_task_id_hex_timestamp(ts_hex: &str) -> bool {
    let Ok(ts) = u64::from_str_radix(ts_hex, 16) else {
        return true;
    };
    let Some(now) = current_unix_ts() else {
        return true;
    };
    let now_u64 = now.max(0) as u64;
    let six_months = SIXTY_SECONDS_U64 * 60 * 24 * 365 / 2;
    let lower = now_u64.saturating_sub(six_months);
    let upper = now_u64.saturating_add(SIXTY_SECONDS_U64);
    ts >= lower && ts <= upper
}

const SIXTY_SECONDS: i64 = 60;
const SIXTY_SECONDS_U64: u64 = 60;

/// 2026-07-01-001 plan U4: best-effort wall clock for the
/// timestamp-window check. Returns `None` when the platform
/// clock is unavailable so the validator falls back to the
/// pre-U4 behaviour. We deliberately do not propagate errors
/// — the projector must keep accepting ids when the clock is
/// missing.
fn current_unix_ts() -> Option<i64> {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .ok()
        .map(|d| d.as_secs() as i64)
}

/// Returns true when `task_key` encodes a ce-executor fix-unit.
/// This is the trigger for the stricter task_id format checks.
fn task_key_is_fix_unit(key: &str) -> bool {
    is_fix_unit_key(key)
}

/// Project a `work.ready` event into the task ledger.
///
/// `key_pointer` is a JSON pointer into the payload (e.g.
/// `"task_key"`, `"step"`); the resolved value becomes the task's
/// stable `key`. `title_pointer` is optional and defaults to `key`.
pub(crate) fn project_ensure_task(
    ctx: &mut ProjectionContext,
    payload: &Value,
    key_pointer: &str,
    title_pointer: Option<&str>,
) -> Result<(), String> {
    let key = json_pointer(payload, key_pointer)
        .ok_or_else(|| format!("missing required pointer '{key_pointer}'"))?
        .to_string();
    let title_source = title_pointer.unwrap_or(key_pointer);
    let title = json_pointer(payload, title_source)
        .unwrap_or(&key)
        .to_string();

    // Apply the change to the in-memory cache first, then persist.
    // We use `with_exclusive_lock` to honour cross-loop writes
    // (rare in Phase 1 but cheap and safe) and to keep the same
    // locking discipline the rest of the orchestrator uses.
    let mut store = TaskStore::load(&ctx.tasks_path).map_err(|e| format!("tasks_load: {e}"))?;
    // Honour the loop's R4 setting from `ProjectionContext` so the
    // projector matches loop behaviour. Previously this hard-coded
    // `false` and silently disabled the R4 gate inside the
    // projector; that bypassed the preset contract — see R1 in
    // docs/plans/2026-06-17-005-fix-state-projection-phase1-review-findings-plan.md.
    store.set_enforce_current_unit(ctx.enforce_current_unit);
    let mut task = Task::new(title, 1).with_key(Some(key.clone()));
    // Honour the payload's `task_id` when the agent supplies one
    // (ce-executor presets always do). Without this the loop
    // would round-trip through a generated id that the agent
    // can never reproduce, breaking the subsequent `work.done`.
    //
    // Fix-1 (2026-06-29 primary-072512 P0): the prior 2026-06-28
    // plan U5 fallback that synthesized `from_key:{key}` when
    // the payload's `task_id` was empty was the root cause of the
    // 4th recurrence of the same pattern group. The synthetic id
    // (a) silently swallowed a contract violation, (b) could not
    // be matched by the subsequent `work.done`, (c) triggered
    // hard-gate exhaustion, and (d) blocked the review/ship/
    // report chain. The preset line 1179 forbids empty
    // `task_id`; we now fail-closed instead of papering over the
    // mistake. The recovery path is the runner injecting
    // schema-level guidance (Fix-2 in `loop_runner/runner.rs`).
    if let Some(provided_id) = json_pointer(payload, "task_id") {
        if provided_id.is_empty() {
            return Err("empty_task_id_in_work_ready: coordinator must embed the \
                 projector-derived id (see preset ce-executor-serial line 1179)"
                .to_string());
        }
        task.id = provided_id.to_string();
    }
    // 2026-06-30 P0-3 (primary-20260629-170451 / primary-20260630-083222):
    // The coordinator's fix-unit prompt template reused the same
    // `task_id` across fix-01 and fix-02 — that landed two candidate
    // rows whose `task_id` matched the wrong row (each `work.done`
    // had to bind to the right `task_key`). The dedup in
    // `TaskStore::ensure` keys on `(loop_id, task_key)`, so reusing a
    // `task_id` across distinct keys still produces two JSONL rows —
    // the runtime tracker in `LoopState` keyed on
    // `(plan, step, task_id)` then loses per-fix-unit identity.
    // Fail-closed at the projection boundary so the coordinator
    // fix-unit prompt is forced to mint a fresh id per
    // (fix_round, fix_unit_index) triple. The restriction applies
    // only to fix-unit keys; ordinary runtime tasks are unaffected.
    if task_key_is_fix_unit(&key)
        && let Some(provided_id) = json_pointer(payload, "task_id")
    {
        let candidate_id = provided_id.to_string();
        // First ensure the format is canonical. This catches hand-written
        // ids before we even check for reuse.
        if !is_valid_task_id_format(&candidate_id) {
            return Err(format!(
                "invalid_task_id_format: '{}' does not match the canonical \
                     task id shapes (task-{{ts}}-{{4hex}} or \
                     task-{{plan_slug}}-fix{{NN}}u{{NN}}-{{ts_hex}}). \
                     Hand-written suffixes such as 'u2' or 'f002' are not allowed; \
                     mint a fresh id per fix-unit via Task::fix_unit_task_id.",
                candidate_id
            ));
        }
        // Task loop_id may not be set yet (it is set below from payload or
        // context). For the reuse check we need the effective loop id the
        // task will end up with, otherwise cross-loop scoping is lost and
        // the lookup returns None.
        let effective_loop_id = ctx_loop_id(payload)
            .map(|s| s.to_string())
            .or_else(|| ctx.current_loop_id.clone());
        if let Some(existing) =
            store.find_open_task_id_in_loop(&candidate_id, effective_loop_id.as_deref())
            && existing.key.as_deref() != Some(key.as_str())
        {
            return Err(format!(
                "task_id_reused_across_keys: work.ready reused open task id \
                         '{}' which is already bound to task_key {:?}; new key is \
                         '{}'. Mint a fresh id per fix-unit via \
                         Task::fix_unit_task_id(plan, fix_round, fix_unit_index, unix_ts).",
                candidate_id, existing.key, key
            ));
        }
    }
    if let Some(plan_name) = json_pointer(payload, "plan_name") {
        task = task.with_description(Some(format!("plan: {plan_name}")));
    }
    // 2026-07-07-002: plan-unit rows created by the projector are owned
    // by the canonical executor hat so close-before-done ACL succeeds.
    // Fix-units keep coordinator ownership (minted via `task ensure --for-fix-unit`).
    if !task_key_is_fix_unit(&key) {
        task = task.with_owner_hat(Some(PLAN_UNIT_OWNER_HAT.to_string()));
    }
    // Reject duplicate task_id bound to a different key (coordinator
    // `task add` racing `work.ready` → projector).
    if let Some(provided_id) = json_pointer(payload, "task_id")
        && !provided_id.is_empty()
        && let Some(existing) = store.get(provided_id)
        && existing.key.as_deref() != Some(key.as_str())
    {
        return Err(format!(
            "duplicate_task_id: id '{provided_id}' is already bound to key \
                         {:?}; work.ready carries key '{key}'. Do not call \
                         `ralph tools task add` before work.ready — the projector is the \
                         sole writer for plan units.",
            existing.key
        ));
    }
    // P0-2 (plan 2026-06-29-006): prefer the payload's `loop_id`
    // when present, otherwise fall back to the loop marker
    // threaded in via `ProjectionContext::current_loop_id`. Without
    // this fallback, executor re-emissions that ship
    // `task_id="from_key:..."` or `task_id=""` produce a task
    // whose `loop_id` is `None`, which is then hard-rejected by
    // `validate_task` as `TaskWrongLoop { actual_loop: None }`
    // (see 2026-06-29-ce-executor-serial-primary-172725 §F3).
    if let Some(loop_id) = ctx_loop_id(payload) {
        task = task.with_loop_id(Some(loop_id.to_string()));
    } else if let Some(loop_id) = ctx.current_loop_id.as_ref() {
        task = task.with_loop_id(Some(loop_id.clone()));
    }
    // R1 (2026-06-17-005 fix plan): when the loop enables R4, the
    // projector must surface single-U collisions as `Err` so the
    // hook can drop the offending event and emit
    // `event.state_projection.rejected`. `TaskStore::ensure`
    // silently returns the existing task on collision (legacy
    // contract); we pre-check so the reject is loud.
    if let Some(collision_idx) = ctx
        .enforce_current_unit
        .then(|| store.find_unit_collision_idx(&task))
        .flatten()
    {
        let sibling = store.all().get(collision_idx);
        let sibling_key = sibling
            .and_then(|t| t.key.as_deref())
            .unwrap_or("<unknown>");
        let sibling_id = sibling.map(|t| t.id.as_str()).unwrap_or("<unknown>");
        return Err(format!(
            "r4_unit_collision: refusing work.ready for task_key='{}' \
             (R4 enforce_current_unit is active; sibling task already open in \
             the same step: sibling_task_id='{}' sibling_task_key='{}')",
            task.key.as_deref().unwrap_or("<no-key>"),
            sibling_id,
            sibling_key,
        ));
    }
    store.ensure(task);
    persist(&ctx.tasks_path, &store, &mut ctx.tasks_cache)
}

/// U2 (plan 2026-07-29-001): per-unit spec built from
/// `EnsureTaskBatch` payloads. `execution_wave` /
/// `integration_order` are `None` when the action does not
/// declare the corresponding pointer (legacy path).
#[derive(Clone)]
struct BatchSpec {
    key: String,
    title: String,
    blocker_keys: Vec<String>,
    execution_wave: Option<u32>,
    integration_order: Option<u32>,
}

pub(crate) fn project_ensure_task_batch(
    ctx: &mut ProjectionContext,
    payload: &Value,
    items_pointer: &str,
    count_pointer: &str,
    key_pointer: &str,
    title_pointer: &str,
    blocked_by_keys_pointer: &str,
    execution_wave_pointer: Option<&str>,
    integration_order_pointer: Option<&str>,
    execution_plan_digest_pointer: Option<&str>,
) -> Result<(), String> {
    let items_value = json_value_pointer(payload, items_pointer)
        .ok_or_else(|| format!("missing required pointer '{items_pointer}'"))?;
    let items = items_value
        .as_array()
        .ok_or_else(|| format!("pointer '{items_pointer}' must be an array"))?;
    if items.is_empty() {
        return Err(format!("pointer '{items_pointer}' must be non-empty"));
    }
    let declared_count = json_value_pointer(payload, count_pointer)
        .and_then(Value::as_u64)
        .and_then(|value| usize::try_from(value).ok())
        .ok_or_else(|| format!("pointer '{count_pointer}' must be a non-negative integer"))?;
    if declared_count != items.len() {
        return Err(format!(
            "count mismatch: '{count_pointer}' is {declared_count}, but '{items_pointer}' has {} items",
            items.len()
        ));
    }

    let mut specs: Vec<BatchSpec> = Vec::with_capacity(items.len());
    let mut keys = HashSet::with_capacity(items.len());
    for (index, item) in items.iter().enumerate() {
        let key = json_pointer(item, key_pointer)
            .filter(|value| !value.trim().is_empty())
            .ok_or_else(|| {
                format!("batch item {index}: missing non-empty pointer '{key_pointer}'")
            })?
            .to_string();
        if !keys.insert(key.clone()) {
            return Err(format!("batch item {index}: duplicate task key '{key}'"));
        }
        let title = json_pointer(item, title_pointer)
            .filter(|value| !value.trim().is_empty())
            .ok_or_else(|| {
                format!(
                    "batch item {index} key '{key}': missing non-empty pointer '{title_pointer}'"
                )
            })?
            .to_string();
        let blocker_values = json_value_pointer(item, blocked_by_keys_pointer)
            .and_then(Value::as_array)
            .ok_or_else(|| {
                format!(
                    "batch item {index} key '{key}': pointer '{blocked_by_keys_pointer}' must be an array"
                )
            })?;
        let mut blocker_keys = Vec::with_capacity(blocker_values.len());
        let mut seen_blockers = HashSet::new();
        for blocker in blocker_values {
            let blocker = blocker.as_str().ok_or_else(|| {
                format!(
                    "batch item {index} key '{key}': '{blocked_by_keys_pointer}' must contain strings"
                )
            })?;
            if blocker == key {
                return Err(format!("batch item {index} key '{key}': self dependency"));
            }
            if !seen_blockers.insert(blocker) {
                return Err(format!(
                    "batch item {index} key '{key}': duplicate dependency '{blocker}'"
                ));
            }
            blocker_keys.push(blocker.to_string());
        }
        // U2 (plan 2026-07-29-001): parse optional static
        // schedule fields when the corresponding pointer is
        // declared on the action. Both pointers must be present
        // together — declaring only one is rejected below in the
        // schedule-validation block.
        let execution_wave = if let Some(ptr) = execution_wave_pointer {
            json_value_pointer(item, ptr)
                .and_then(Value::as_u64)
                .and_then(|v| u32::try_from(v).ok())
        } else {
            None
        };
        let integration_order = if let Some(ptr) = integration_order_pointer {
            json_value_pointer(item, ptr)
                .and_then(Value::as_u64)
                .and_then(|v| u32::try_from(v).ok())
        } else {
            None
        };
        specs.push(BatchSpec {
            key,
            title,
            blocker_keys,
            execution_wave,
            integration_order,
        });
    }
    for spec in &specs {
        for blocker in &spec.blocker_keys {
            if !keys.contains(blocker) {
                return Err(format!(
                    "batch item key '{}': unknown dependency '{blocker}'",
                    spec.key
                ));
            }
        }
    }
    reject_dependency_cycles(
        &specs
            .iter()
            .map(|spec| {
                (
                    spec.key.as_str(),
                    spec.blocker_keys.iter().map(String::as_str).collect(),
                )
            })
            .collect::<Vec<(&str, Vec<&str>)>>(),
    )?;

    // U2 (plan 2026-07-29-001): static wave/order schedule validation.
    //
    // Activation rule: when **both** `execution_wave_pointer` and
    // `integration_order_pointer` are present on the action, the
    // payload must declare a valid schedule. When neither pointer
    // is present, skip validation (legacy path — preserves the
    // behaviour for non-Parallel-Forge presets). Declaring only
    // one pointer is a configuration error and rejects the batch.
    match (execution_wave_pointer, integration_order_pointer) {
        (None, None) => {}
        (Some(_), None) | (None, Some(_)) => {
            return Err(
                "EnsureTaskBatch schedule validation requires both                  `execution_wave` and `integration_order` pointers to be                  declared; only one was set"
                    .to_string(),
            );
        }
        (Some(_), Some(_)) => {
            validate_wave_schedule(&specs, execution_plan_digest_pointer, payload)?;
        }
    }

    let loop_id = ctx.current_loop_id.clone();
    let mut store = TaskStore::load(&ctx.tasks_path).map_err(|e| format!("tasks_load: {e}"))?;
    store.set_enforce_current_unit(ctx.enforce_current_unit);
    store.try_with_exclusive_lock(|store| {
        let mut live_ids = HashMap::with_capacity(specs.len());
        let mut used_ids = store
            .all()
            .iter()
            .map(|task| task.id.clone())
            .collect::<HashSet<_>>();

        for spec in &specs {
            if let Some(existing) = store.get_by_key_in_loop(&spec.key, loop_id.as_deref()) {
                if existing.title != spec.title
                    || existing.owner_hat_id.as_deref() != Some("executor")
                {
                    return Err(format!(
                        "batch item key '{}': existing task metadata conflicts",
                        spec.key
                    ));
                }
                live_ids.insert(spec.key.clone(), existing.id.clone());
            } else {
                let id = mint_unique_task_id(&mut used_ids)?;
                live_ids.insert(spec.key.clone(), id);
            }
        }

        for spec in &specs {
            let blocked_by = spec
                .blocker_keys
                .iter()
                .map(|key| live_ids.get(key).cloned().unwrap())
                .collect::<Vec<_>>();
            if let Some(existing) = store.get_by_key_in_loop(&spec.key, loop_id.as_deref()) {
                if existing.blocked_by != blocked_by {
                    return Err(format!(
                        "batch item key '{}': existing dependency graph conflicts",
                        spec.key
                    ));
                }
                continue;
            }
            let mut task = Task::new(spec.title.clone(), 1)
                .with_key(Some(spec.key.clone()))
                .with_loop_id(loop_id.clone())
                .with_owner_hat(Some(PLAN_UNIT_OWNER_HAT.to_string()));
            task.id = live_ids[&spec.key].clone();
            task.blocked_by = blocked_by;
            store.add(task);
        }
        Ok(())
    })?;
    ctx.tasks_cache = store.all().to_vec();
    Ok(())
}

fn json_value_pointer<'a>(value: &'a Value, pointer: &str) -> Option<&'a Value> {
    if pointer.is_empty() {
        return Some(value);
    }
    pointer
        .split('.')
        .try_fold(value, |current, segment| current.get(segment))
}

fn mint_unique_task_id(used_ids: &mut HashSet<String>) -> Result<String, String> {
    for _ in 0..256 {
        let candidate = Task::generate_id();
        if used_ids.insert(candidate.clone()) {
            return Ok(candidate);
        }
    }
    Err("unable to mint a unique task id after 256 attempts".to_string())
}

fn reject_dependency_cycles(specs: &[(&str, Vec<&str>)]) -> Result<(), String> {
    fn visit(
        key: &str,
        graph: &HashMap<&str, Vec<&str>>,
        visiting: &mut HashSet<String>,
        visited: &mut HashSet<String>,
    ) -> Result<(), String> {
        if visited.contains(key) {
            return Ok(());
        }
        if !visiting.insert(key.to_string()) {
            return Err(format!("batch dependency cycle includes '{key}'"));
        }
        for dependency in graph.get(key).into_iter().flatten() {
            visit(dependency, graph, visiting, visited)?;
        }
        visiting.remove(key);
        visited.insert(key.to_string());
        Ok(())
    }

    let graph = specs.iter().cloned().collect::<HashMap<_, _>>();
    let mut visiting = HashSet::new();
    let mut visited = HashSet::new();
    for key in graph.keys() {
        visit(key, &graph, &mut visiting, &mut visited)?;
    }
    Ok(())
}

pub(crate) fn project_close_task(
    ctx: &mut ProjectionContext,
    payload: &Value,
    task_id_pointer: &str,
    step_pointer: Option<&str>,
) -> Result<(), String> {
    let task_id = json_pointer(payload, task_id_pointer)
        .ok_or_else(|| format!("missing required pointer '{task_id_pointer}'"))?
        .to_string();

    let mut store = TaskStore::load(&ctx.tasks_path).map_err(|e| format!("tasks_load: {e}"))?;
    // 2026-06-30 P0-2 (primary-153653): when multiple tasks share
    // the same task_id (coordinator emits the same id for fix-01
    // and fix-02 because the agent's prompt template reuses it),
    // `store.close(&task_id)` only closes the **first** row with
    // that id (`TaskStore::get_mut` returns the first match) —
    // later fix-unit rows stay `open` forever, producing the
    // P0-3 tasks.jsonl ↔ progress.md drift. When the payload also
    // carries a `task_key` (always present in ce-executor-serial
    // payloads), look up by key first; the key is unique per
    // step including fix-NN, so the close targets the right row.
    // Fall back to id lookup when no key is available so legacy
    // payloads keep working.
    // 2026-06-30 P0-2 (primary-153653): when multiple tasks share
    // the same task_id (coordinator emits the same id for fix-01
    // and fix-02 because the agent's prompt template reuses it),
    // `store.close(&task_id)` only closes the **first** row with
    // that id (`TaskStore::get_mut` returns the first match) —
    // later fix-unit rows stay `open` forever, producing the
    // P0-3 tasks.jsonl ↔ progress.md drift. When the payload also
    // carries a `task_key` (always present in ce-executor-serial
    // payloads), look up by key first; the key is unique per
    // step including fix-NN, so the close targets the right row.
    // Fall back to id lookup when no key is available so legacy
    // payloads keep working.
    enum CloseOutcome {
        Closed,
        Missing,
    }
    // 2026-06-30-001 P0-4: the `work.done` projector path
    // is the only legitimate way a task gets closed without
    // an explicit `TaskStore::start` call (executor picks
    // the task up between `work.ready` and `work.done`,
    // and never calls start). Mark the row as started here
    // so the new `TaskStore::close_by_key` /
    // `TaskStore::close` `started.is_none()` guard (added
    // in P0-4 to prevent orphan closed tasks for
    // placeholder rows) accepts the close. Fix-unit tasks
    // (matched by `is_fix_unit_key`) skip this branch —
    // they are exempt from the guard by design (see
    // `TaskStore::close_by_key`).
    //
    // Pre-fix behaviour: the projector just called
    // `close_by_key`. Post-fix: the close still happens,
    // but the row is first marked started so the
    // never-started placeholder rows that the diagnose
    // report P0-4 is targeting remain rejected (they
    // never go through `work.done`).
    let mut outcome = CloseOutcome::Missing;
    if let Some(task_key) = json_pointer(payload, "task_key") {
        if let Some(row) = store.get_by_key_mut(task_key) {
            if row.started.is_none() && !is_fix_unit_key(task_key) {
                row.start();
            }
            if store.close_by_key(task_key).is_some() {
                outcome = CloseOutcome::Closed;
            }
        } else {
            // Key mismatch — fall back to id lookup so we don't
            // silently no-op on malformed payloads.
            if let Some(row) = store.get_mut(&task_id)
                && row.started.is_none()
                && !is_fix_unit_id(&task_id)
            {
                row.start();
            }
            if store.close(&task_id).is_some() {
                outcome = CloseOutcome::Closed;
            }
        }
    } else if let Some(row) = store.get_mut(&task_id) {
        if row.started.is_none() && !is_fix_unit_id(&task_id) {
            row.start();
        }
        if store.close(&task_id).is_some() {
            outcome = CloseOutcome::Closed;
        }
    }
    match outcome {
        CloseOutcome::Closed => {}
        CloseOutcome::Missing => {
            // Fail-closed: a `work.done` referencing a task_id
            // that is not in the ledger is a contract
            // violation. The existing `progress_task_gate` will
            // also reject it; we refuse to silently no-op.
            return Err(format!("task_not_found: {task_id}"));
        }
    }
    persist(&ctx.tasks_path, &store, &mut ctx.tasks_cache)?;

    // If the event also carries a `step`, advance the progress
    // ledger. We delegate the progress write to the progress
    // sub-module to keep one source of truth.
    if let Some(step) = step_pointer
        .and_then(|p| json_pointer(payload, p))
        .map(|s| s.to_string())
    {
        crate::state_projector::progress::project_close_step(ctx, &step)
    } else {
        Ok(())
    }
}

/// U3 of plan 2026-07-29-001
/// (`fix-parallel-forge-static-wave-settlement-plan`):
/// atomically close the set of tasks named in a
/// `forge.wave.settled` payload.
///
/// Invariants (R7/R14, scenario S3, unit-test split §11):
/// 1. Empty input → fail-closed (no task is touched).
/// 2. Duplicate `task_id`s in the payload → fail-closed.
/// 3. Any unknown `task_id` (not in the ledger) → fail-closed
///    with zero side effects.
/// 4. Identity drift: mixed open/closed batch is fail-closed.
///    A batch that is **entirely** already-closed is an
///    idempotent no-op (replay-friendly, matches the U2
///    `EnsureTaskBatch` replay contract).
/// 5. Atomicity: every close is staged in memory, then
///    persisted exactly once. Any pre-validation failure leaves
///    the ledger untouched.
///
/// The projector consumes the array at `task_ids_pointer` (a
/// JSON pointer relative to the event payload). The action
/// carries no `step` field — wave settlement is a task-ledger
/// concept, not a progress-gate concept; the progress module
/// stays untouched.
pub(crate) fn project_close_task_batch(
    ctx: &mut ProjectionContext,
    payload: &Value,
    task_ids_pointer: &str,
) -> Result<(), String> {
    // `json_pointer` is string-only — for an array we have to
    // hand-route through the raw payload. This keeps the pointer
    // contract aligned with the rest of the projector (string
    // pointer → string value) while letting specs embed a JSON
    // array under a top-level key.
    let raw = lookup_pointer(payload, task_ids_pointer)
        .ok_or_else(|| format!("missing required pointer '{task_ids_pointer}'"))?;

    let arr = raw.as_array().ok_or_else(|| {
        format!(
            "close_task_batch: pointer '{task_ids_pointer}' must resolve to an array \
             (got {})",
            type_of_value(raw)
        )
    })?;

    if arr.is_empty() {
        return Err("close_task_batch: empty task_ids array".to_string());
    }

    // Pre-validate identities (duplicate detection is the cheapest
    // check; run it before opening the ledger so we don't pay for
    // a reload on malformed payloads).
    let mut seen: std::collections::HashSet<String> = std::collections::HashSet::new();
    let mut task_ids: Vec<String> = Vec::with_capacity(arr.len());
    for (idx, v) in arr.iter().enumerate() {
        let id = v.as_str().ok_or_else(|| {
            format!(
                "close_task_batch: task_ids[{idx}] is not a string (got {})",
                type_of_value(v)
            )
        })?;
        if id.is_empty() {
            return Err(format!("close_task_batch: task_ids[{idx}] is empty"));
        }
        if !seen.insert(id.to_string()) {
            return Err(format!(
                "close_task_batch: duplicate task_id '{id}' in batch"
            ));
        }
        task_ids.push(id.to_string());
    }

    let mut store = TaskStore::load(&ctx.tasks_path).map_err(|e| format!("tasks_load: {e}"))?;

    // Validate every target ID exists, and the open/closed
    // distribution is either "all open" (active settlement) or
    // "all closed" (idempotent replay). Mixed states are identity
    // drift and must fail.
    let mut any_open = false;
    let mut any_closed = false;
    let mut all_ids: Vec<&str> = Vec::with_capacity(task_ids.len());
    for id in &task_ids {
        match store.get(id) {
            Some(row) => {
                if row.closed.is_some() {
                    any_closed = true;
                } else {
                    any_open = true;
                }
                all_ids.push(id.as_str());
            }
            None => {
                return Err(format!("close_task_batch: unknown task_id '{id}'"));
            }
        }
    }
    if any_open && any_closed {
        return Err(
            "close_task_batch: task_id batch mixes open and closed rows \
             (identity drift — reject to avoid silent partial close)"
                .to_string(),
        );
    }

    // Idempotent replay: every target already closed → no-op.
    if !any_open {
        return Ok(());
    }

    // Active settlement: every target open → close all.
    //
    // U5 of plan 2026-07-29-005 (G9, R14, AE-G5): the batch close
    // runs on a staging clone of `store.tasks` so any per-id failure
    // leaves the on-disk ledger and `ctx.tasks_cache` byte-identical
    // to the pre-call state. The clone is cheap (a `Vec<Task>`
    // per-row copy) and only ever reaches `persist` when every id
    // closes successfully.
    //
    // Post-review fix (#4): the close mutation is shared via
    // `Task::mark_closed`, and the defensive-start guard mirrors
    // `TaskStore::close`'s fix-unit exemption — a fix-unit id is
    // closed with `started` left untouched (`None`), exactly as the
    // single-row `project_close_task` path does. Previously this loop
    // called `row.start()` unconditionally, which wrote
    // `started=Some(now)` for never-started fix-units and produced a
    // different ledger than the single-close path for the same task.
    let mut staging = store.tasks().to_vec();
    for id in &task_ids {
        let target = staging.iter_mut().find(|t| t.id == *id);
        let Some(row) = target else {
            return Err(format!("close_task_batch: failed to close task_id '{id}'"));
        };
        // Defensive start (P0-4) for never-started rows, EXCEPT
        // fix-units: `is_fix_unit_id` mirrors `TaskStore::close`'s
        // guard so fix-unit rows keep `started=None` on both paths.
        if row.started.is_none() && !is_fix_unit_id(&row.id) {
            row.start();
        }
        row.mark_closed();
    }
    // Commit: only NOW do we touch the live store + disk + cache.
    store.replace_tasks_for_atomic_batch(staging);
    persist(&ctx.tasks_path, &store, &mut ctx.tasks_cache)?;
    Ok(())
}

fn type_of_value(v: &Value) -> &'static str {
    match v {
        Value::Null => "null",
        Value::Bool(_) => "bool",
        Value::Number(_) => "number",
        Value::String(_) => "string",
        Value::Array(_) => "array",
        Value::Object(_) => "object",
    }
}

/// Resolve a dotted JSON pointer against an arbitrary JSON
/// value. Unlike `json_pointer` (string-only), this returns the
/// raw `Value` so non-string payloads (arrays, objects) can be
/// consumed by actions like `CloseTaskBatch`. Returns `None`
/// when any segment is missing.
fn lookup_pointer<'a>(value: &'a Value, pointer: &str) -> Option<&'a Value> {
    if pointer.is_empty() {
        return Some(value);
    }
    let mut current = value;
    for segment in pointer.split('.') {
        current = current.get(segment)?;
    }
    Some(current)
}

fn persist(_path: &Path, store: &TaskStore, cache: &mut Vec<Task>) -> Result<(), String> {
    // `_path` is reserved for a future diagnostic event that
    // records the on-disk write site (e.g. via the
    // `ralph_diagnostics` collector). The path lives on the
    // context already; carrying it through `persist` keeps the
    // signature stable for that extension.
    store.save().map_err(|e| format!("tasks_save: {e}"))?;
    *cache = store.all().to_vec();
    Ok(())
}

fn ctx_loop_id(payload: &Value) -> Option<&str> {
    json_pointer(payload, "loop_id")
}

#[cfg(test)]
mod tests {
    //! P0-2 (plan 2026-06-29-006): the projector must fall back
    //! to `ProjectionContext::current_loop_id` when an event
    //! payload omits the `loop_id` field. Without the fallback,
    //! tasks projected from `task_id="from_key:..."` legacy
    //! emissions stay `loop_id=None` and trigger
    //! `TaskWrongLoop { actual_loop: None }` in `validate_task`.

    use super::*;
    use crate::state_projector::StateProjectionConfig;
    use tempfile::tempdir;

    fn ctx_with_loop_marker(workspace: &Path, loop_id: &str) -> ProjectionContext {
        ProjectionContext::new(workspace, StateProjectionConfig::default(), false)
            .with_current_loop_id(loop_id)
    }

    fn payload_with_task_id(task_id: &str, task_key: &str) -> Value {
        serde_json::json!({
            "task_id": task_id,
            "task_key": task_key,
            "plan_name": "test-plan",
        })
    }

    #[test]
    fn project_task_with_payload_loop_id_uses_payload() {
        let dir = tempdir().unwrap();
        let mut ctx = ctx_with_loop_marker(dir.path(), "loop-A");
        let payload = payload_with_task_id("task-1234-a1b2", "k-1");
        let payload_with_loop = serde_json::json!({
            "task_id": "task-1234-a1b2",
            "task_key": "k-1",
            "plan_name": "test-plan",
            "loop_id": "loop-B",
        });
        project_ensure_task(&mut ctx, &payload_with_loop, "task_key", None).unwrap();
        let tasks = ctx.task_snapshot().0;
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].loop_id.as_deref(), Some("loop-B"));
        // Reference unused variables to silence lints.
        let _ = payload;
    }

    #[test]
    fn project_task_falls_back_to_ctx_loop_id_when_payload_missing() {
        let dir = tempdir().unwrap();
        let mut ctx = ctx_with_loop_marker(dir.path(), "loop-A");
        let payload = payload_with_task_id("task-1234-a1b2", "k-1");
        project_ensure_task(&mut ctx, &payload, "task_key", None).unwrap();
        let tasks = ctx.task_snapshot().0;
        assert_eq!(tasks.len(), 1);
        assert_eq!(
            tasks[0].loop_id.as_deref(),
            Some("loop-A"),
            "P0-2: when payload has no `loop_id`, projector must use the loop marker"
        );
    }

    #[test]
    fn project_task_with_no_loop_id_anywhere_stays_none() {
        let dir = tempdir().unwrap();
        // No loop marker in ctx, no loop_id in payload.
        let mut ctx = ProjectionContext::new(dir.path(), StateProjectionConfig::default(), false);
        let payload = payload_with_task_id("task-1234-a1b2", "k-1");
        project_ensure_task(&mut ctx, &payload, "task_key", None).unwrap();
        let tasks = ctx.task_snapshot().0;
        assert_eq!(tasks.len(), 1);
        // Loop_id is None — preserve pre-fix behaviour for
        // non-loop-scoped presets that don't set a marker.
        assert_eq!(tasks[0].loop_id, None);
    }

    // Fix-1 (2026-06-29 primary-072512 P0): empty task_id must
    // be rejected by the projector instead of silently falling
    // back to `from_key:{key}`. The 4th recurrence of the same
    // pattern group caused the hard gate to exhaust on step-04
    // because `work.ready(task_id="")` produced a synthetic
    // task that the subsequent `work.done` could not match.
    #[test]
    fn project_task_rejects_empty_task_id() {
        let dir = tempdir().unwrap();
        let mut ctx = ctx_with_loop_marker(dir.path(), "loop-A");
        let payload = serde_json::json!({
            "task_id": "",
            "task_key": "ce-executor:test:step-01:u0-impl",
            "plan_name": "test-plan",
        });
        let result = project_ensure_task(&mut ctx, &payload, "task_key", None);
        assert!(
            result.is_err(),
            "Fix-1: empty task_id must fail-closed (was: silently fell back to from_key:)"
        );
        let err = result.unwrap_err();
        assert!(
            err.contains("empty_task_id"),
            "error must name the root cause: got {err}"
        );
        // No task should have been written to the ledger.
        let tasks = ctx.task_snapshot().0;
        assert!(
            tasks.is_empty(),
            "Fix-1: rejected event must not write to ledger (was: wrote synthetic from_key: task)"
        );
    }

    // 2026-06-30 P0-2 (primary-153653): fix-01 and fix-02
    // shared the same task_id in the JSONL because the
    // coordinator's fix-unit prompt template copied it. Closing
    // by id alone only closed the first row, leaving the rest
    // `open` forever and producing the P0-3 tasks.jsonl ↔
    // progress.md drift. The projector now prefers `task_key`
    // when present, then falls back to id. Regression test:
    // ensure two fix-units with the same task_id but different
    // task_keys, close each via work.done carrying the right
    // task_key, and verify both rows end up closed.
    #[test]
    fn p0_2_fix_units_share_task_id_close_by_key_independently() {
        use crate::state_projector::ProjectionContext;
        use crate::state_projector::StateProjectionConfig;

        let dir = tempdir().unwrap();
        let mut ctx = ProjectionContext::new(dir.path(), StateProjectionConfig::default(), false)
            .with_current_loop_id("loop-A");
        // Two fix-units with distinct task_ids (the required shape after
        // the P0-3 guard was added), different task_keys. Close each via
        // work.done carrying the right task_key and verify both rows end
        // up closed. This preserves the original regression coverage:
        // close routes by task_key, not by task_id alone.
        let fix01_ensure = serde_json::json!({
            "task_id": "task-1782811846-3de0",
            "task_key": "ce-executor:p:fix-01:u1",
            "plan_name": "p",
        });
        let fix02_ensure = serde_json::json!({
            "task_id": "task-1782811847-a1b2",
            "task_key": "ce-executor:p:fix-02:u2",
            "plan_name": "p",
        });
        project_ensure_task(&mut ctx, &fix01_ensure, "task_key", None).unwrap();
        project_ensure_task(&mut ctx, &fix02_ensure, "task_key", None).unwrap();

        let fix01_close = serde_json::json!({
            "task_id": "task-1782811846-3de0",
            "task_key": "ce-executor:p:fix-01:u1",
            "step": "fix-01",
        });
        let fix02_close = serde_json::json!({
            "task_id": "task-1782811847-a1b2",
            "task_key": "ce-executor:p:fix-02:u2",
            "step": "fix-02",
        });
        project_close_task(&mut ctx, &fix01_close, "task_id", Some("step")).unwrap();
        project_close_task(&mut ctx, &fix02_close, "task_id", Some("step")).unwrap();

        let tasks = ctx.task_snapshot().0;
        assert_eq!(tasks.len(), 2, "two fix-units must both be persisted");
        let closed_keys: Vec<&str> = tasks
            .iter()
            .filter(|t| t.status == crate::task::TaskStatus::Closed)
            .filter_map(|t| t.key.as_deref())
            .collect();
        assert_eq!(
            closed_keys.len(),
            2,
            "P0-2: both fix-units must close when task_key differs (was: only first closes)"
        );
    }

    // 2026-06-30 P0-1 (primary-20260629-170451 diagnosis):
    // The pre-fix projector wrote `progress.md` with an empty
    // heading when `current_step` happened to be `None` mid-
    // phase, surfacing `WARN: progress.md written with empty
    // headings` to the validator's prompt and producing the
    // "0 ready / 0 open / N closed" line that aborted fix-02
    // with no `test.passed`. The fix lives in the progress
    // sub-module (see `state_projector/progress.rs`); here
    // we only assert the projector hands off a stable
    // snapshot to the progress writer. Regression test:
    // ensure two fix-units and close them in order; verify
    // both rows terminate `Closed` and a third `work.done`
    // for a missing key surfaces `task_not_found` as before.
    #[test]
    fn p0_1_close_unstarted_task_is_unchanged() {
        use crate::state_projector::ProjectionContext;
        use crate::state_projector::StateProjectionConfig;

        let dir = tempdir().unwrap();
        let mut ctx = ProjectionContext::new(dir.path(), StateProjectionConfig::default(), false)
            .with_current_loop_id("loop-A");
        // fix-unit rows are created and closed without ever
        // being explicitly `start`-ed, by coordinator design.
        // The projector must close them anyway so the validator
        // can move past fix-02 (this is the path that was
        // broken by an over-eager "skip unstarted" guard
        // introduced in an earlier iteration of this fix;
        // the right fix lives in `progress.rs`).
        // 2026-07-01-001 plan U4: helper-derive these ids so the
        // validator's 6-month back-window accepts them. The
        // historical hand-written `task-p-fix01u01-a1b2` /
        // `b2c3` ids used 1970-era hex that now falls outside
        // the window.
        let fix01_ensure = serde_json::json!({
            "task_id": Task::fix_unit_task_id("p", 1, 1, None),
            "task_key": "ce-executor:p:fix-01:u1",
            "plan_name": "p",
        });
        let fix02_ensure = serde_json::json!({
            "task_id": Task::fix_unit_task_id("p", 1, 2, None),
            "task_key": "ce-executor:p:fix-02:u2",
            "plan_name": "p",
        });
        project_ensure_task(&mut ctx, &fix01_ensure, "task_key", None).unwrap();
        project_ensure_task(&mut ctx, &fix02_ensure, "task_key", None).unwrap();

        let fix01_close = serde_json::json!({
            "task_id": Task::fix_unit_task_id("p", 1, 1, None),
            "task_key": "ce-executor:p:fix-01:u1",
            "step": "fix-01",
        });
        let fix02_close = serde_json::json!({
            "task_id": Task::fix_unit_task_id("p", 1, 2, None),
            "task_key": "ce-executor:p:fix-02:u2",
            "step": "fix-02",
        });
        project_close_task(&mut ctx, &fix01_close, "task_id", Some("step")).unwrap();
        project_close_task(&mut ctx, &fix02_close, "task_id", Some("step")).unwrap();

        let tasks = ctx.task_snapshot().0;
        let closed_keys: Vec<&str> = tasks
            .iter()
            .filter(|t| t.status == crate::task::TaskStatus::Closed)
            .filter_map(|t| t.key.as_deref())
            .collect();
        assert_eq!(
            closed_keys.len(),
            2,
            "P0-1: both fix-units must close (started guard was a regression)"
        );

        // Closing a non-existent row still fails closed.
        let bogus = serde_json::json!({
            "task_id": "task-9999-dead",
            "task_key": "ce-executor:p:fix-99:u99",
            "step": "fix-99",
        });
        let err = project_close_task(&mut ctx, &bogus, "task_id", Some("step"))
            .expect_err("unknown task_key must surface task_not_found");
        assert!(err.contains("task_not_found"), "got: {err}");
    }

    // Post-review fix (#4): the batch settlement path must close
    // fix-unit rows with `started` left untouched (`None`), exactly
    // like the single-row `project_close_task` path above. Before
    // the fix, `project_close_task_batch` called `row.start()`
    // unconditionally and wrote `started=Some(now)` for never-started
    // fix-units, so the same task produced a different ledger
    // depending on whether it was closed singly or in a batch. This
    // test seeds two never-started fix-units, batch-closes them via
    // `forge.wave.settled`, and asserts the close succeeded while
    // `started` stayed `None` on both rows.
    #[test]
    fn batch_close_fix_units_keeps_started_none() {
        use crate::state_projector::ProjectionContext;
        use crate::state_projector::StateProjectionConfig;

        let dir = tempdir().unwrap();
        let mut ctx = ProjectionContext::new(dir.path(), StateProjectionConfig::default(), false)
            .with_current_loop_id("loop-A");
        // Pin a single ts so the ensure() ids and the payload ids
        // below are byte-identical (see p0_3 for the drift rationale).
        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);
        let fix01_id = Task::fix_unit_task_id("p", 1, 1, Some(ts));
        let fix02_id = Task::fix_unit_task_id("p", 1, 2, Some(ts));

        // Fix-units are created without an intervening start, by
        // coordinator design.
        project_ensure_task(
            &mut ctx,
            &serde_json::json!({
                "task_id": fix01_id,
                "task_key": "ce-executor:p:fix-01:u1",
                "plan_name": "p",
            }),
            "task_key",
            None,
        )
        .unwrap();
        project_ensure_task(
            &mut ctx,
            &serde_json::json!({
                "task_id": fix02_id,
                "task_key": "ce-executor:p:fix-02:u2",
                "plan_name": "p",
            }),
            "task_key",
            None,
        )
        .unwrap();

        // Sanity: both rows exist and were never started.
        {
            let tasks = ctx.task_snapshot().0;
            assert_eq!(tasks.len(), 2);
            for t in tasks {
                assert!(t.started.is_none(), "fix-unit must start life unstarted");
            }
        }

        // Batch-close both via the settlement projection.
        let payload = serde_json::json!({
            "wave_id": "w1",
            "settled_task_ids": [fix01_id.clone(), fix02_id.clone()],
        });
        project_close_task_batch(&mut ctx, &payload, "settled_task_ids")
            .expect("batch close of fix-units must succeed");

        // Both closed, and crucially `started` is still `None`
        // (the single-close parity this fix restores).
        let tasks = ctx.task_snapshot().0;
        assert_eq!(tasks.len(), 2);
        for t in tasks {
            assert_eq!(
                t.status,
                crate::task::TaskStatus::Closed,
                "fix-unit {} must be closed by the batch",
                t.id
            );
            assert!(
                t.started.is_none(),
                "fix-unit {} must keep started=None after batch close (was: written by unconditional start())",
                t.id
            );
            assert!(
                t.closed.is_some(),
                "fix-unit {} must record a close ts",
                t.id
            );
        }
    }

    #[test]
    fn p0_3_reused_task_id_with_different_key_is_rejected_for_fix_units() {
        use crate::state_projector::ProjectionContext;
        use crate::state_projector::StateProjectionConfig;

        let dir = tempdir().unwrap();
        let mut ctx = ProjectionContext::new(dir.path(), StateProjectionConfig::default(), false)
            .with_current_loop_id("loop-A");
        // Pin a single ts so every `fix_unit_task_id` call below
        // yields the same id string. `None` would re-read
        // `SystemTime::now()` at each call site and a 1-second
        // drift between the ensure() and the trailing assert_eq!
        // produces `task-...-{ts:x}` and `task-...-{ts+1:x}`,
        // which fail the id equality assertion (regression from
        // 02101d32 switching the test body to helper-derive ids).
        let ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);
        // First emit: fresh id + fix-01 key.
        // 2026-07-01-001 plan U4: helper-derive the id so the
        // validator's 6-month back-window accepts it. The
        // historical `task-ce_executor_serial-fix01u01-1` had
        // a 1970-era hex suffix and now falls outside.
        let fix_unit_id = Task::fix_unit_task_id("ce-executor-serial", 1, 1, Some(ts));
        let fix01 = serde_json::json!({
            "task_id": fix_unit_id.clone(),
            "task_key": "ce-executor:p:fix-01:u1",
            "plan_name": "p",
        });
        project_ensure_task(&mut ctx, &fix01, "task_key", None).unwrap();
        let tasks = ctx.task_snapshot().0;
        assert_eq!(tasks.len(), 1);
        assert_eq!(tasks[0].id, fix_unit_id);

        // Second emit: same id, but fix-02 key — must fail-closed.
        let fix02 = serde_json::json!({
            "task_id": fix_unit_id.clone(),
            "task_key": "ce-executor:p:fix-02:u2",
            "plan_name": "p",
        });
        let result = project_ensure_task(&mut ctx, &fix02, "task_key", None);
        assert!(
            result.is_err(),
            "P0-3: reusing an open task id for a different fix-unit task_key must be rejected"
        );
        let err = result.unwrap_err();
        assert!(
            err.contains("task_id_reused_across_keys"),
            "error must name the root cause: got {err}"
        );

        // Only the original row is written; no second ledger entry.
        let tasks = ctx.task_snapshot().0;
        assert_eq!(tasks.len(), 1, "rejected emit must not write a second row");
        assert_eq!(tasks[0].key.as_deref(), Some("ce-executor:p:fix-01:u1"));
    }

    #[test]
    fn ordinary_task_id_reuse_across_keys_is_rejected() {
        // 2026-07-07-002 P0-2: the projector is the sole writer for
        // plan-unit task rows. Reusing a `task_id` across different
        // ordinary (non-fix-unit) keys was a legacy pattern that
        // produced duplicate rows shadowing the keyed live row — the
        // exact shape that stalled the 2026-07-07 e2e. The projector
        // now rejects this regardless of fix-unit status. This test
        // pins the new contract: same id + different key = hard error,
        // and only the first row is written.
        use crate::state_projector::ProjectionContext;
        use crate::state_projector::StateProjectionConfig;

        let dir = tempdir().unwrap();
        let mut ctx = ProjectionContext::new(dir.path(), StateProjectionConfig::default(), false)
            .with_current_loop_id("loop-A");
        let first = serde_json::json!({
            "task_id": "task-shared",
            "task_key": "legacy:step-01:impl",
            "plan_name": "p",
        });
        let second = serde_json::json!({
            "task_id": "task-shared",
            "task_key": "legacy:step-02:impl",
            "plan_name": "p",
        });
        project_ensure_task(&mut ctx, &first, "task_key", None).unwrap();
        let err = project_ensure_task(&mut ctx, &second, "task_key", None)
            .expect_err("reuse of task_id across different keys must be rejected");
        assert!(
            err.contains("duplicate_task_id"),
            "error must carry structured reason, got: {err}"
        );

        // Only the original row is written; no second ledger entry.
        let tasks = ctx.task_snapshot().0;
        assert_eq!(
            tasks.len(),
            1,
            "rejected projection must not write a second row"
        );
        assert_eq!(tasks[0].key.as_deref(), Some("legacy:step-01:impl"));
    }

    // 2026-06-30 P0-B (primary-20260630-083222): the coordinator's
    // fix-unit prompt template hand-wrote task ids such as
    // `task-1782813211-u2` (suffix `u2` is not 4 hex chars) and
    // stray ids like `f002` / `3b7d`. The projector now validates
    // the task id format for fix-unit payloads so these malformed ids
    // are rejected at the boundary instead of silently entering tasks.jsonl.
    #[test]
    fn p0_b_invalid_task_id_format_for_fix_unit_is_rejected() {
        use crate::state_projector::ProjectionContext;
        use crate::state_projector::StateProjectionConfig;

        let dir = tempdir().unwrap();
        let mut ctx = ProjectionContext::new(dir.path(), StateProjectionConfig::default(), false)
            .with_current_loop_id("loop-A");

        for bad_id in [
            "task-1782813211-u2", // suffix not hex
            "not-a-task-id",
            "task-",
            "task-1234-zzzz", // hex chars invalid
        ] {
            let payload = serde_json::json!({
                "task_id": bad_id,
                "task_key": "ce-executor:p:fix-02:u2",
                "plan_name": "p",
            });
            let result = project_ensure_task(&mut ctx, &payload, "task_key", None);
            assert!(
                result.is_err(),
                "invalid task id '{}' must be rejected",
                bad_id
            );
            let err = result.unwrap_err();
            assert!(
                err.contains("invalid_task_id_format"),
                "error must name the root cause for '{}': got {}",
                bad_id,
                err
            );
        }

        // Valid canonical ids are still accepted.
        for good_id in ["task-1782811846-3de0", "task-ce_executor_serial-fix01u01-1"] {
            let payload = serde_json::json!({
                "task_id": good_id,
                "task_key": format!("ce-executor:p:fix-good:{}", good_id),
                "plan_name": "p",
            });
            project_ensure_task(&mut ctx, &payload, "task_key", None)
                .unwrap_or_else(|e| panic!("valid task id '{}' rejected: {e}", good_id));
        }

        // Chinese plan names are sanitized to a valid slug by
        // Task::fix_unit_task_id; the projector must accept them.
        // 2026-07-01-001 plan U4: pass a current-loop unix_ts
        // so the helper output falls inside the validator's
        // 18-month back-window (the historical `Some(1)` value
        // corresponds to 1970-01-01 and now fails the
        // timestamp-window check).
        let now_ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        let chinese_id = Task::fix_unit_task_id("中文方案-001", 0, 0, Some(now_ts));
        assert!(
            is_valid_task_id_format(&chinese_id),
            "fix_unit_task_id output for chinese plan must be accepted: {chinese_id}"
        );
    }

    #[test]
    fn ordinary_task_id_format_is_not_enforced() {
        use crate::state_projector::ProjectionContext;
        use crate::state_projector::StateProjectionConfig;

        let dir = tempdir().unwrap();
        let mut ctx = ProjectionContext::new(dir.path(), StateProjectionConfig::default(), false)
            .with_current_loop_id("loop-A");

        // Non-fix-unit payloads must not be rejected for non-canonical
        // task ids — this preserves compatibility with legacy presets,
        // human CLI, and tests.
        for loose_id in ["task-1", "task-fix01", "task-1782813211-u2", "task-abc-def"] {
            let payload = serde_json::json!({
                "task_id": loose_id,
                "task_key": format!("legacy:step:{}", loose_id),
                "plan_name": "p",
            });
            project_ensure_task(&mut ctx, &payload, "task_key", None).unwrap_or_else(|e| {
                panic!("legacy task id '{}' should not be rejected: {e}", loose_id)
            });
        }
    }

    // 2026-06-30 P0-3 (primary-140433 diagnosis):
    //
    // The fixture for this run records `task_id="task-1782830434-abcd"`
    // emitted by the coordinator fix-02 path. That id matches the
    // schema shape (`task-{ts}-{4hex}`), so the projection boundary
    // accepts it even though the agent hand-wrote the unix_ts plus
    // a hex suffix (`1782830434` + `abcd`) instead of using the
    // canonical `Task::fix_unit_task_id` helper (see
    // `crates/ralph-core/src/task.rs::fix_unit_task_id`).
    //
    // The runtime cannot differentiate the hand-written shape-1 id
    // from one derived through the helper today — both match the
    // lenient validator. This test pins two invariants:
    //  1. The hand-written fixture id is observed by the lenient
    //     validator (shape-1 acceptance is real, not theoretical),
    //     so any future runtime tightening that rejects it must be
    //     explicit, not implicit.
    //  2. The helper output is always accepted across unicode plan
    //     names and arbitrary ts / no-ts inputs.
    //
    // If the runtime is later tightened so that fix-unit `task_id`
    // must be derived through `Task::fix_unit_task_id` (a future
    // P0-3 follow-up), this test should be updated to assert the
    // rejection for the hand-written id while keeping the helper
    // acceptance assertion.
    #[test]
    fn p0_3_fix_unit_pinned_to_fix_unit_task_id_helper() {
        // 1. The hand-written id from the fixture passes through
        //    the lenient schema validator today. The runtime cannot
        //    differentiate shape-1 from helper-derived ids.
        let hand_written = "task-1782830434-abcd";
        assert!(
            is_valid_task_id_format(hand_written),
            "shape-1 ids pass the lenient validator today; runtime \
             cannot differentiate hand-written from helper-derived. \
             Any future tightening must explicitly reject this id.",
        );

        // 2. The helper output is always accepted, including for
        //    unicode plan names and arbitrary ts / no-ts.
        //    2026-07-01-001 plan U4: pass current-loop unix_ts
        //    values so the helper output stays inside the
        //    validator's 6-month back-window. The historical
        //    `Some(0x1782_8312_3456u64)` value decoded to
        //    >5000 years in the future and now falls outside.
        let now_ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        for (plan, fr, ui, ts) in [
            (
                "ce-executor:2026-06-20-001-feat-python-sort",
                0,
                1,
                Some(now_ts),
            ),
            ("simple-plan", 0, 1, None),
            ("中文方案", 2, 3, Some(now_ts)),
        ] {
            let id = Task::fix_unit_task_id(plan, fr, ui, ts);
            assert!(
                is_valid_task_id_format(&id),
                "Task::fix_unit_task_id output must always pass \
                 the lenient validator: {id} (plan={plan})",
            );
        }

        // 3. The fix-unit key embeds `fix-{NN}`, so the fix-unit
        //    path of `project_ensure_task` is exercised by any
        //    payload whose `task_key` matches that shape.
        let fix_unit_key = "ce-executor:p:fix-02:u2";
        assert!(
            is_fix_unit_key(fix_unit_key),
            "the fixture-style fix-unit key must register as fix-unit",
        );

        // 4. A helper-derived id and the hand-written id differ in
        //    structure — the prompt should route the coordinator
        //    through the helper instead of copy-pasting a unix_ts.
        //    2026-07-01-001 plan U4: use a current-loop unix_ts
        //    so the helper output passes the validator's 18-month
        //    back-window (the legacy `0x1782_8304_34` value
        //    corresponds to 2021 and now falls outside).
        let now_ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        let good_id = Task::fix_unit_task_id("p", 0, 2, Some(now_ts));
        assert_ne!(good_id, hand_written);
    }

    // 2026-07-01-001 plan U4 (primary-20260630-175407 P0-3):
    // hand-written `task-1751414400-a1b2` carried a 2025-07-01
    // timestamp that the lenient shape-1 validator silently
    // accepted. Window-check the unix_ts segment of shape-1 ids
    // and the hex segment of shape-2 ids so the legacy leniency
    // can no longer poison the task ledger. The validator runs
    // against `is_valid_task_id_format` directly so we do not
    // need to spin up a ProjectionContext for this unit-level
    // invariant.
    #[test]
    fn u4_stale_shape1_timestamp_is_rejected() {
        // 2025-07-01 timestamp — the exact fixture id from
        // `primary-20260630-175407`. Was accepted pre-U4; must
        // be rejected now that the validator window-checks the
        // unix_ts segment.
        assert!(!is_valid_task_id_format("task-1751414400-a1b2"));
    }

    #[test]
    fn u4_current_loop_timestamp_is_accepted() {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        let id = format!("task-{now}-abcd");
        assert!(is_valid_task_id_format(&id));
    }

    #[test]
    fn u4_future_timestamp_is_rejected() {
        let far_future = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs()
            + 3600; // 1 hour into the future
        let id = format!("task-{far_future}-abcd");
        assert!(!is_valid_task_id_format(&id));
    }

    #[test]
    fn u4_helper_derived_id_is_accepted() {
        // The helper mints shape-2 ids. Use a current-loop
        // unix_ts so the validator's 18-month back-window
        // accepts the helper output (the historical
        // `0x1782_8304_34` value decodes to 2021 and now
        // falls outside the window).
        let now_ts = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        let id = Task::fix_unit_task_id("p", 0, 2, Some(now_ts));
        assert!(is_valid_task_id_format(&id));
    }

    #[test]
    fn u4_stale_shape2_hex_timestamp_is_rejected() {
        // Hand-written hex timestamp equivalent to 2025-07-01
        // (~1.75e9). The validator must window-check it.
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        let old = now.saturating_sub(2 * 365 * 24 * 3600); // 2 years ago
        let id = format!("task-ce_executor_serial-fix02u02-{old:x}");
        assert!(!is_valid_task_id_format(&id));
    }
}

/// U2 (plan 2026-07-29-001): validate the static `execution_wave` /
/// `integration_order` schedule for an `EnsureTaskBatch` payload.
///
/// Rules (matches plan §5/§6 + KTD1):
///   1. Every unit must declare both fields when this validator runs.
///   2. `execution_wave` is a positive integer (`u32 > 0`).
///   3. `integration_order` is a positive integer (`u32 > 0`).
///   4. `execution_wave` values form a contiguous sequence
///      starting at 1 with no gaps (`max_wave == n_waves`).
///   5. `integration_order` values are unique across all units
///      and form a contiguous sequence 1..=n.
///   6. For every dep edge `unit <- dep`: `wave(dep) < wave(unit)`.
///   7. For every dep edge: `order(dep) < order(unit)`.
///   8. When `execution_plan_digest_pointer` resolves, the digest
///      value must be a non-empty string.
///
/// The validator is `O(V + E)` because every unit and every dep
/// edge are visited exactly once. Rejection messages include the
/// offending item key / edge / rule so the operator can pinpoint
/// the source of the inconsistency.
fn validate_wave_schedule(
    specs: &[BatchSpec],
    execution_plan_digest_pointer: Option<&str>,
    payload: &Value,
) -> Result<(), String> {
    // Rule 1: every unit must declare both fields.
    for spec in specs {
        match (spec.execution_wave, spec.integration_order) {
            (Some(w), Some(o)) if w > 0 && o > 0 => {}
            _ => {
                return Err(format!(
                    "schedule field missing or non-positive:                      unit '{}' execution_wave={:?} integration_order={:?}                      (both must be positive integers)",
                    spec.key, spec.execution_wave, spec.integration_order,
                ));
            }
        }
    }

    // Rule 4: wave must be a contiguous sequence starting at 1.
    let max_wave = specs
        .iter()
        .filter_map(|s| s.execution_wave)
        .max()
        .unwrap_or(0);
    let wave_set: std::collections::HashSet<u32> =
        specs.iter().filter_map(|s| s.execution_wave).collect();
    for w in 1..=max_wave {
        if !wave_set.contains(&w) {
            return Err(format!(
                "schedule wave not consecutive: missing wave {w}                  (declared waves: {sorted})",
                sorted = {
                    let mut v: Vec<u32> = wave_set.iter().copied().collect();
                    v.sort();
                    v.iter()
                        .map(|x| x.to_string())
                        .collect::<Vec<_>>()
                        .join(",")
                }
            ));
        }
    }
    // wave 0 (and any other non-positive) is rejected by Rule 1
    // above; we additionally guard against the upper-bound having
    // been declared as 0 by checking the max again.
    if max_wave == 0 {
        return Err(
            "schedule wave set is empty: every unit must declare              execution_wave >= 1"
                .to_string(),
        );
    }

    // Rule 5: integration_order unique and contiguous 1..=n.
    let n = specs.len();
    let mut order_seen = std::collections::HashSet::with_capacity(n);
    for spec in specs {
        let o = spec.integration_order.expect("Rule 1 already checked");
        if !order_seen.insert(o) {
            return Err(format!(
                "schedule integration_order duplicate: order {o} appears on                  multiple units (e.g. '{}')",
                spec.key
            ));
        }
        if o as usize > n {
            return Err(format!(
                "schedule integration_order exceeds unit count:                  order {o} > unit_count {n}",
            ));
        }
    }
    // Contiguity 1..=n must hold.
    for o in 1..=n as u32 {
        if !order_seen.contains(&o) {
            return Err(format!(
                "schedule integration_order not consecutive: missing order {o}                  (unit_count={n})",
            ));
        }
    }

    // Build a quick key -> spec lookup for dep-edge checks.
    let key_index: std::collections::HashMap<&str, &BatchSpec> =
        specs.iter().map(|s| (s.key.as_str(), s)).collect();

    // Rules 6 & 7: dep edges must respect wave and order monotonicity.
    for spec in specs {
        let my_wave = spec.execution_wave.expect("Rule 1 already checked");
        let my_order = spec.integration_order.expect("Rule 1 already checked");
        for dep in &spec.blocker_keys {
            let dep_spec = key_index.get(dep.as_str()).copied().ok_or_else(|| {
                format!(
                    "schedule dep edge unknown dependency:                      unit '{}' -> dep '{}' (no such unit)",
                    spec.key, dep
                )
            })?;
            let dep_wave = dep_spec.execution_wave.expect("Rule 1 already checked");
            let dep_order = dep_spec.integration_order.expect("Rule 1 already checked");
            if dep_wave >= my_wave {
                return Err(format!(
                    "schedule wave invariant violated:                      dep '{}' (wave {}) is not strictly less than                      unit '{}' (wave {})",
                    dep, dep_wave, spec.key, my_wave,
                ));
            }
            if dep_order >= my_order {
                return Err(format!(
                    "schedule integration_order invariant violated:                      dep '{}' (order {}) is not strictly less than                      unit '{}' (order {})",
                    dep, dep_order, spec.key, my_order,
                ));
            }
        }
    }

    // Rule 8: digest must resolve to a non-empty string when the
    // pointer is set.
    if let Some(ptr) = execution_plan_digest_pointer {
        let digest = json_value_pointer(payload, ptr)
            .and_then(Value::as_str)
            .ok_or_else(|| {
                format!("execution_plan_digest pointer '{ptr}' missing or not a string")
            })?;
        let trimmed = digest.trim();
        if trimmed.is_empty() {
            return Err(format!("execution_plan_digest pointer '{ptr}' is empty"));
        }
    }

    Ok(())
}
