//! Preset template metadata and template catalog models.
//!
//! This module provides types for:
//! - `x_preset`: Authoring metadata attached to generated preset YAML files
//! - `TemplateManifest`: Catalog entries describing available templates
//! - `Version`: SemVer-compatible version parsing and comparison
//!
//! These types are CLI-only (authoring layer) and do NOT enter ralph-core runtime.

use serde::{Deserialize, Serialize};
use std::cmp::Ordering;
use std::fmt;
use std::str::FromStr;

/// Schema version for `x_preset` metadata.
/// Currently fixed at `1`. Future versions may introduce breaking changes
/// to the metadata structure.
pub const X_PRESET_SCHEMA_VERSION: i64 = 1;

/// Check profile for generated presets.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum CheckProfile {
    /// Authoring checks only: YAML parse, config load.
    Authoring,
    /// Strict checks: payload schemas, topology validation.
    Strict,
    /// Full runtime-ready checks including preflight.
    RuntimeReady,
}

impl Default for CheckProfile {
    fn default() -> Self {
        CheckProfile::Authoring
    }
}

impl fmt::Display for CheckProfile {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            CheckProfile::Authoring => write!(f, "authoring"),
            CheckProfile::Strict => write!(f, "strict"),
            CheckProfile::RuntimeReady => write!(f, "runtime-ready"),
        }
    }
}

/// `x_preset` metadata attached to generated preset YAML files.
///
/// This struct captures authoring metadata that helps with:
/// - Template provenance tracking
/// - Version diff and upgrade preview
/// - Diagnostics attribution
///
/// Note: `RalphConfig::parse_yaml()` ignores unknown top-level fields,
/// so `x_preset` is transparent to the runtime.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct XPresetMetadata {
    /// Schema version. Must be `1` for this version of the metadata spec.
    pub schema_version: i64,

    /// Name of the template used to generate this preset.
    pub template: String,

    /// Template version when the preset was generated (SemVer string).
    pub template_version: String,

    /// Tool that generated this preset.
    pub generated_by: String,

    /// ISO 8601 / RFC3339 timestamp when the preset was generated.
    pub generated_at: String,

    /// User-specified name for the generated preset.
    pub name: String,

    /// User-specified description for the generated preset.
    pub description: String,

    /// Which checks are recommended for this preset.
    #[serde(default)]
    pub check_profile: CheckProfile,

    /// Optional Ralph version compatibility range (e.g., ">=0.2.0").
    /// Currently informational only; not enforced by the runtime.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ralph_compat: Option<String>,
}

impl XPresetMetadata {
    /// Parse `x_preset` from a raw YAML value.
    ///
    /// Returns `Ok(Some(...))` if `x_preset` key exists and is valid.
    /// Returns `Ok(None)` if `x_preset` key is absent (old preset).
    /// Returns `Err(...)` if `x_preset` exists but is malformed.
    pub fn from_yaml_value(value: &serde_yaml::Value) -> Result<Option<Self>, XPresetParseError> {
        let Some(x_preset) = value.get("x_preset") else {
            return Ok(None);
        };

        let raw: serde_yaml::Value = x_preset.clone();

        let metadata: XPresetMetadata = serde_yaml::from_value(raw)
            .map_err(|e| XPresetParseError::Deserialization(e.to_string()))?;

        // Validate schema version
        if metadata.schema_version != X_PRESET_SCHEMA_VERSION {
            return Err(XPresetParseError::UnsupportedSchemaVersion {
                found: metadata.schema_version,
                supported: X_PRESET_SCHEMA_VERSION,
            });
        }

        // Validate template name is non-empty
        if metadata.template.is_empty() {
            return Err(XPresetParseError::MissingRequiredField {
                field: "template".to_string(),
            });
        }

        // Validate template version is parseable
        if Version::from_str(&metadata.template_version).is_err() {
            return Err(XPresetParseError::InvalidTemplateVersion {
                value: metadata.template_version.clone(),
            });
        }

        Ok(Some(metadata))
    }

    /// Returns true if this metadata indicates a preset generated by `ralph preset new`.
    pub fn is_generated(&self) -> bool {
        self.generated_by.starts_with("ralph preset")
    }
}

/// Errors that can occur when parsing `x_preset` metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum XPresetParseError {
    /// YAML syntax error while parsing the `x_preset` node.
    YamlSyntax(String),

    /// Deserialization failed for one or more fields.
    Deserialization(String),

    /// The `schema_version` is not supported.
    UnsupportedSchemaVersion { found: i64, supported: i64 },

    /// A required field is missing or empty.
    MissingRequiredField { field: String },

    /// The `template_version` is not a valid version string.
    InvalidTemplateVersion { value: String },
}

impl fmt::Display for XPresetParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            XPresetParseError::YamlSyntax(msg) => {
                write!(f, "x_preset YAML syntax error: {}", msg)
            }
            XPresetParseError::Deserialization(e) => {
                write!(f, "x_preset deserialization error: {}", e)
            }
            XPresetParseError::UnsupportedSchemaVersion { found, supported } => {
                write!(
                    f,
                    "unsupported x_preset schema version: {} (supported: {})",
                    found, supported
                )
            }
            XPresetParseError::MissingRequiredField { field } => {
                write!(f, "x_preset missing required field: '{}'", field)
            }
            XPresetParseError::InvalidTemplateVersion { value } => {
                write!(
                    f,
                    "x_preset template_version is not a valid version: '{}'",
                    value
                )
            }
        }
    }
}

impl std::error::Error for XPresetParseError {}

/// Template difficulty level.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum TemplateDifficulty {
    Beginner,
    Intermediate,
    Advanced,
}

impl Default for TemplateDifficulty {
    fn default() -> Self {
        TemplateDifficulty::Beginner
    }
}

/// Placeholder variable defined by a template.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TemplatePlaceholder {
    /// Placeholder name (used as `{{name}}` in template).
    pub name: String,

    /// Human-readable description of the placeholder.
    pub description: String,

    /// Default value if user does not provide one.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub default: Option<String>,
}

/// Template catalog entry describing an available workflow template.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TemplateManifest {
    /// Unique template identifier.
    pub name: String,

    /// Template version (SemVer string).
    pub version: String,

    /// Human-readable description of the template.
    pub description: String,

    /// Category for grouping templates (e.g., "development", "review", "research").
    #[serde(default)]
    pub category: String,

    /// Difficulty level.
    #[serde(default)]
    pub difficulty: TemplateDifficulty,

    /// Which builtin preset this template is based on (if any).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,

    /// Recommended check profile for generated presets.
    #[serde(default)]
    pub recommended_checks: CheckProfile,

    /// Placeholders this template supports.
    #[serde(default)]
    pub placeholders: Vec<TemplatePlaceholder>,

    /// Additional notes about what this template produces.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_notes: Option<String>,
}

impl TemplateManifest {
    /// Returns true if this template is suitable for beginners.
    pub fn is_beginner_friendly(&self) -> bool {
        self.difficulty == TemplateDifficulty::Beginner
    }

    /// Returns the list of required placeholder names.
    pub fn required_placeholders(&self) -> Vec<&str> {
        self.placeholders
            .iter()
            .filter(|p| p.default.is_none())
            .map(|p| p.name.as_str())
            .collect()
    }
}

/// A semantic version (MAJOR.MINOR.PATCH[-prerelease][+build]).
///
/// This is a minimal implementation supporting:
/// - Parsing and formatting standard SemVer strings
/// - Equality, ordering (by major, minor, patch, prerelease)
/// - Rejection of malformed versions
///
/// For full SemVer compliance including prerelease ordering rules,
/// consider using the `semver` crate.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Version {
    pub major: u64,
    pub minor: u64,
    pub patch: u64,
    pub prerelease: Option<String>,
    pub build: Option<String>,
}

impl Ord for Version {
    fn cmp(&self, other: &Self) -> Ordering {
        // Compare major.minor.patch first
        self.major
            .cmp(&other.major)
            .then_with(|| self.minor.cmp(&other.minor))
            .then_with(|| self.patch.cmp(&other.patch))
            .then_with(|| {
                // SemVer: a release version (no prerelease) is greater than a prerelease
                // with the same major.minor.patch
                match (&self.prerelease, &other.prerelease) {
                    (None, None) => Ordering::Equal,
                    (None, Some(_)) => Ordering::Greater,
                    (Some(_), None) => Ordering::Less,
                    (Some(a), Some(b)) => a.cmp(b),
                }
            })
    }
}

impl PartialOrd for Version {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Version {
    /// Parse a SemVer string.
    ///
    /// Accepts: `1.0.0`, `1.2.3-alpha`, `1.2.3-alpha.1`, `1.2.3+build`, `1.2.3-alpha+build`
    /// Rejects: versions without all three major.minor.patch components,
    ///          negative numbers, non-numeric components.
    pub fn parse(s: &str) -> Result<Self, VersionError> {
        let original = s;

        // Split off build metadata
        let (core, build) = if let Some((core, build)) = s.split_once('+') {
            if build.is_empty() {
                return Err(VersionError::EmptyBuildMetadata);
            }
            (core, Some(build.to_string()))
        } else {
            (s, None)
        };

        // Split off prerelease
        let (core, prerelease) = if let Some((core, pre)) = core.split_once('-') {
            if pre.is_empty() {
                return Err(VersionError::EmptyPrerelease);
            }
            validate_prerelease(pre)?;
            (core, Some(pre.to_string()))
        } else {
            (core, None)
        };

        // Parse major.minor.patch
        let parts: Vec<&str> = core.split('.').collect();
        if parts.len() != 3 {
            return Err(VersionError::InvalidFormat {
                expected: "MAJOR.MINOR.PATCH".to_string(),
                found: original.to_string(),
            });
        }

        let major = parse_component(parts[0], "major", original)?;
        let minor = parse_component(parts[1], "minor", original)?;
        let patch = parse_component(parts[2], "patch", original)?;

        Ok(Version {
            major,
            minor,
            patch,
            prerelease,
            build,
        })
    }

    /// Returns true if this version is compatible with `other` per SemVer rules.
    ///
    /// Two versions are compatible if they have the same major version and
    /// the other version is at least as high in major.minor.patch.
    pub fn is_compatible_with(&self, other: &Version) -> bool {
        self.major == other.major
            && (self.minor < other.minor
                || (self.minor == other.minor && self.patch <= other.patch))
    }

    /// Returns the minimum version with the same major.minor.patch.
    pub fn patch_min(&self) -> Version {
        Version {
            major: self.major,
            minor: self.minor,
            patch: self.patch,
            prerelease: None,
            build: None,
        }
    }
}

/// Validate prerelease string per SemVer spec: ASCII identifiers separated by dots,
/// each identifier must only contain ASCII alphanumerics and hyphens.
fn validate_prerelease(pre: &str) -> Result<(), VersionError> {
    if pre.is_empty() {
        return Err(VersionError::EmptyPrerelease);
    }

    for identifier in pre.split('.') {
        if identifier.is_empty() {
            return Err(VersionError::EmptyPrereleaseIdentifier);
        }
        for byte in identifier.bytes() {
            let is_valid = byte.is_ascii_alphanumeric() || byte == b'-';
            if !is_valid {
                return Err(VersionError::InvalidPrereleaseCharacter {
                    character: byte as char,
                    identifier: pre.to_string(),
                });
            }
        }
    }

    Ok(())
}

fn parse_component(s: &str, name: &str, original: &str) -> Result<u64, VersionError> {
    if s.is_empty() {
        return Err(VersionError::InvalidFormat {
            expected: format!("{} (a non-negative integer)", name),
            found: original.to_string(),
        });
    }

    // Reject leading zeros (except for "0" itself)
    if s.len() > 1 && s.starts_with('0') {
        return Err(VersionError::LeadingZero {
            component: name.to_string(),
            value: s.to_string(),
        });
    }

    s.parse::<u64>()
        .map_err(|_| VersionError::NonNumericComponent {
            component: name.to_string(),
            value: s.to_string(),
        })
}

/// Errors that can occur when parsing a version string.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VersionError {
    /// The version string does not contain exactly three numeric components.
    InvalidFormat { expected: String, found: String },

    /// A version component is not a non-negative integer.
    NonNumericComponent { component: String, value: String },

    /// A component has a leading zero (except for "0" itself).
    LeadingZero { component: String, value: String },

    /// Prerelease tag is empty.
    EmptyPrerelease,

    /// Prerelease contains an empty identifier (e.g., "alpha." or ".1").
    EmptyPrereleaseIdentifier,

    /// Prerelease contains an invalid character (only ASCII alphanumerics and hyphens allowed).
    InvalidPrereleaseCharacter { character: char, identifier: String },

    /// Build metadata is empty.
    EmptyBuildMetadata,
}

impl fmt::Display for VersionError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            VersionError::InvalidFormat { expected, found } => {
                write!(
                    f,
                    "invalid version format: expected {}, found '{}'",
                    expected, found
                )
            }
            VersionError::NonNumericComponent { component, value } => {
                write!(
                    f,
                    "version {} component must be a non-negative integer, found '{}'",
                    component, value
                )
            }
            VersionError::LeadingZero { component, value } => {
                write!(
                    f,
                    "version {} component '{}' has leading zero (must be '0' or no leading zero)",
                    component, value
                )
            }
            VersionError::EmptyPrerelease => {
                write!(f, "prerelease tag cannot be empty")
            }
            VersionError::EmptyPrereleaseIdentifier => {
                write!(
                    f,
                    "prerelease identifier cannot be empty (e.g., 'alpha.' or '.1' are invalid)"
                )
            }
            VersionError::InvalidPrereleaseCharacter {
                character,
                identifier,
            } => {
                write!(
                    f,
                    "prerelease identifier '{}' contains invalid character '{}' (only ASCII alphanumerics and hyphens allowed)",
                    identifier, character
                )
            }
            VersionError::EmptyBuildMetadata => {
                write!(f, "build metadata cannot be empty")
            }
        }
    }
}

impl std::error::Error for VersionError {}

impl FromStr for Version {
    type Err = VersionError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Version::parse(s)
    }
}

impl fmt::Display for Version {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}.{}.{}", self.major, self.minor, self.patch)?;
        if let Some(ref pre) = self.prerelease {
            write!(f, "-{}", pre)?;
        }
        if let Some(ref build) = self.build {
            write!(f, "+{}", build)?;
        }
        Ok(())
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Template Catalog and Safe Renderer
// ─────────────────────────────────────────────────────────────────────────────

use std::collections::HashMap;

/// Well-known placeholder names that templates may use.
/// The renderer only substitutes these exact names.
const ALLOWED_PLACEHOLDERS: &[&str] = &[
    "preset_name",
    "description",
    "author",
    "generated_at",
    "starting_event",
    "completion_promise",
];

/// Errors that can occur during template rendering.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RenderError {
    /// A placeholder was found that is not in the allowlist.
    UnknownPlaceholder { name: String },

    /// A required placeholder has no value provided.
    MissingPlaceholderValue { name: String },

    /// The template YAML is malformed.
    InvalidYaml { source: String },

    /// The generated YAML cannot be parsed back.
    YamlParseError { source: String },
}

impl fmt::Display for RenderError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            RenderError::UnknownPlaceholder { name } => {
                write!(
                    f,
                    "unknown placeholder '{{{{{}}}}}': not in allowlist. Allowed: {:?}",
                    name, ALLOWED_PLACEHOLDERS
                )
            }
            RenderError::MissingPlaceholderValue { name } => {
                write!(
                    f,
                    "required placeholder '{{{{{}}}}}' has no value provided",
                    name
                )
            }
            RenderError::InvalidYaml { source } => {
                write!(f, "template YAML is invalid: {}", source)
            }
            RenderError::YamlParseError { source } => {
                write!(f, "rendered YAML cannot be parsed: {}", source)
            }
        }
    }
}

impl std::error::Error for RenderError {}

/// Renders a preset template by substituting placeholders.
///
/// This is a SAFE renderer: it only substitutes known placeholders
/// and rejects unknown ones to prevent template injection.
pub struct TemplateRenderer;

impl TemplateRenderer {
    /// Render a template string with the given placeholder values.
    ///
    /// Returns an error if:
    /// - An unknown placeholder is found (not in allowlist)
    /// - A required placeholder has no value
    ///
    /// # Arguments
    /// * `template` - The template string containing `{{placeholder}}` markers
    /// * `values` - Map of placeholder names to their values
    ///
    /// # Example
    /// ```
    /// let rendered = TemplateRenderer::render(
    ///     "name: {{preset_name}}",
    ///     &[("preset_name", "my-flow")],
    /// ).unwrap();
    /// assert_eq!(rendered, "name: my-flow");
    /// ```
    pub fn render(template: &str, values: &[(&str, &str)]) -> Result<String, RenderError> {
        let value_map: HashMap<&str, &str> = values.iter().cloned().collect();

        // First pass: check for unknown placeholders
        for line in template.lines() {
            let stripped = line.trim();
            // Match {{placeholder}} pattern
            let mut search = stripped;
            while let Some(start) = search.find("{{") {
                let after_start = &search[start + 2..];
                if let Some(end) = after_start.find("}}") {
                    let placeholder = &after_start[..end];
                    let trimmed = placeholder.trim();
                    if !ALLOWED_PLACEHOLDERS.contains(&trimmed) {
                        return Err(RenderError::UnknownPlaceholder {
                            name: trimmed.to_string(),
                        });
                    }
                    search = &after_start[end + 2..];
                } else {
                    break;
                }
            }
        }

        // Second pass: substitute placeholders with YAML-quoted values.
        // String-level substitution is lossy: a user value containing `:`,
        // `"`, `#`, a reserved indicator at start, or control characters
        // would produce broken YAML. We pre-quote every value into a
        // YAML double-quoted scalar (which is unambiguous) before
        // substitution, then verify the result parses as YAML.
        let mut result = template.to_string();
        for (name, value) in &value_map {
            let safe_value = yaml_quote_scalar(value);
            let placeholder = format!("{{{{{}}}}}", name);
            result = result.replace(&placeholder, &safe_value);
        }

        // Third pass: check for any remaining unsubstituted required placeholders
        for placeholder in ALLOWED_PLACEHOLDERS {
            let marker = format!("{{{{{}}}}}", placeholder);
            if result.contains(&marker) {
                // Check if this placeholder is required (not in values with a default)
                if !value_map.contains_key(placeholder) {
                    return Err(RenderError::MissingPlaceholderValue {
                        name: placeholder.to_string(),
                    });
                }
            }
        }

        // Fourth pass (defense-in-depth): verify the rendered output is
        // valid YAML. The static template is valid and every substituted
        // value is now a properly-escaped YAML double-quoted scalar, so
        // parsing should always succeed. If it doesn't, the template is
        // broken or a code path produced an unsafe value; surface a clear
        // error rather than writing a corrupt file.
        serde_yaml::from_str::<serde_yaml::Value>(&result).map_err(|e| {
            RenderError::YamlParseError {
                source: format!(
                    "rendered output is not valid YAML: {} (this is a renderer bug)",
                    e
                ),
            }
        })?;

        Ok(result)
    }

    /// Validate that a template string only uses allowed placeholders.
    /// Unlike `render`, this does NOT require values for the placeholders.
    pub fn validate_placeholders(template: &str) -> Result<(), RenderError> {
        // Check for unknown placeholders only (don't require values)
        for line in template.lines() {
            let stripped = line.trim();
            let mut search = stripped;
            while let Some(start) = search.find("{{") {
                let after_start = &search[start + 2..];
                if let Some(end) = after_start.find("}}") {
                    let placeholder = &after_start[..end];
                    let trimmed = placeholder.trim();
                    if !ALLOWED_PLACEHOLDERS.contains(&trimmed) {
                        return Err(RenderError::UnknownPlaceholder {
                            name: trimmed.to_string(),
                        });
                    }
                    search = &after_start[end + 2..];
                } else {
                    break;
                }
            }
        }
        Ok(())
    }
}

/// Quote a user-supplied value as a YAML scalar (plain or double-quoted)
/// so that string-level substitution into a YAML template cannot break
/// the surrounding document.
///
/// Strategy:
/// - If the value is safe as a YAML plain scalar, return it unchanged.
///   This keeps simple preset names / descriptions readable in the
///   generated file (e.g., `name: my-flow`).
/// - Otherwise, emit a YAML double-quoted scalar with proper escapes.
///   This is the safe path that handles every value round-trippably,
///   including `:` ambiguity, reserved indicators, control chars, and
///   values that look like bool/null/int/float.
///
/// The "needs quoting" rules below are the conservative subset of YAML
/// 1.2 plain-scalar rules that, if missed, would cause a plain-scalar
/// emission to either fail to parse or coerce to a non-string type.
fn yaml_quote_scalar(value: &str) -> String {
    if needs_quoting(value) {
        quote_as_double_quoted(value)
    } else {
        value.to_string()
    }
}

/// Return true if `value` cannot be safely emitted as a YAML plain scalar.
fn needs_quoting(value: &str) -> bool {
    if value.is_empty() {
        return true;
    }

    // Leading or trailing whitespace changes the plain-scalar semantics.
    if value != value.trim() {
        return true;
    }

    // Reserved indicator characters at the start of a plain scalar
    // (YAML 1.2 §7.3.3). Including them unquoted would change the
    // document's structure.
    const RESERVED_START: &[char] = &[
        '-', '?', ':', ',', '[', ']', '{', '}', '#', '&', '*', '!', '|', '>', '\'', '"', '%', '@',
        '`',
    ];
    if let Some(first) = value.chars().next() {
        if RESERVED_START.contains(&first) {
            return true;
        }
    }

    for ch in value.chars() {
        // Any control character forces quoting (we don't want raw \0,
        // \x01, etc. in config files). \t/\n/\r are handled by the
        // double-quoted escape table.
        if ch.is_control() {
            return true;
        }
    }

    // ": " (colon-space) and ":\n" are the canonical "this looks like
    // a key-value pair" patterns. We do NOT force-quote every colon
    // (timestamps like `2026-06-09T03:22:06Z` have a `:` followed by
    // digits, which is unambiguous as a plain scalar).
    if contains_key_value_separator(value) {
        return true;
    }

    // " #" (space-hash) is the comment marker in flow context. Hash at
    // the start of a line is the block comment marker; we already handle
    // that via the reserved-start check.
    if value.contains(" #") {
        return true;
    }

    // Lookalike scalars: avoid accidentally coercing to bool/null/int/float.
    if looks_like_non_string_scalar(value) {
        return true;
    }

    false
}

/// Conservative check: does `value` look like a non-string YAML scalar?
/// (YAML 1.2 core schema types.)
fn looks_like_non_string_scalar(value: &str) -> bool {
    matches!(
        value,
        // bool (YAML 1.2 core schema)
        "true" | "false" | "True" | "False" | "TRUE" | "FALSE"
        // null
        | "null" | "Null" | "NULL" | "~" // int / float — start with a digit, optional sign
    ) || (value
        .chars()
        .next()
        .map_or(false, |c| c.is_ascii_digit() || c == '-' || c == '+')
        && value.chars().all(|c| {
            c.is_ascii_digit() || c == '.' || c == 'e' || c == 'E' || c == '+' || c == '-'
        }))
}

/// Returns true if `value` contains a YAML key-value separator pattern
/// inside a plain scalar that would be ambiguous. The two patterns are
/// `: ` (colon-space, the block-mapping separator) and `:\n` (colon
/// followed by end of line, which can also be read as a block key).
///
/// We deliberately do NOT flag a bare `:` (e.g., timestamps like
/// `2026-06-09T03:22:06Z`) because the surrounding plain scalar context
/// makes the colon unambiguous: there is no space and no line break, so
/// the value parses as a single plain scalar.
fn contains_key_value_separator(value: &str) -> bool {
    let bytes = value.as_bytes();
    for (i, &b) in bytes.iter().enumerate() {
        if b == b':' {
            if i + 1 < bytes.len()
                && (bytes[i + 1] == b' ' || bytes[i + 1] == b'\n' || bytes[i + 1] == b'\t')
            {
                return true;
            }
        }
    }
    false
}

/// Emit `value` as a YAML 1.2 double-quoted scalar with full escaping.
fn quote_as_double_quoted(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            '\0' => out.push_str("\\0"),
            c if c.is_control() => {
                // Other control chars: emit as a \uXXXX escape. This
                // round-trips through serde_yaml back to the same string.
                out.push_str(&format!("\\u{:04X}", c as u32));
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod yaml_quote_tests {
    use super::{needs_quoting, quote_as_double_quoted, yaml_quote_scalar};

    #[test]
    fn plain_scalar_unchanged_for_safe_inputs() {
        // Simple alphanumerics, hyphens, underscores, dots, slashes, parens
        // should pass through as plain scalars.
        for input in [
            "my-flow",
            "test-flow2",
            "A simple two-hat linear workflow for learning and small tasks",
            "Team code assist workflow",
            "Planner",
            "code-assist",
        ] {
            assert!(
                !needs_quoting(input),
                "expected plain-scalar pass-through for {:?}",
                input
            );
            assert_eq!(yaml_quote_scalar(input), input, "input: {:?}", input);
        }
    }

    #[test]
    fn quote_when_empty() {
        assert_eq!(yaml_quote_scalar(""), "\"\"");
    }

    #[test]
    fn quote_when_starts_with_reserved_indicator() {
        for input in ["-dash", "?question", ":colon", "#hash", "&amp", "*star"] {
            assert!(needs_quoting(input), "input: {:?}", input);
            assert_eq!(
                yaml_quote_scalar(input),
                format!("\"{}\"", input),
                "input: {:?}",
                input
            );
        }
    }

    #[test]
    fn quote_when_contains_key_value_separator() {
        // ": " (colon-space) is the canonical "looks like a key-value
        // pair" pattern that forces quoting.
        for input in [
            "Test with: colon",
            "key: value",
            "trailing colon: ", // ends with ": "
        ] {
            assert!(needs_quoting(input), "input: {:?}", input);
        }
    }

    #[test]
    fn plain_scalar_passes_through_bare_colon() {
        // A bare `:` (not followed by space/newline/tab) is fine in a
        // plain scalar. This is the timestamp case:
        // `2026-06-09T03:22:06.764181066+00:00` is unambiguous.
        for input in [
            "no:colon:here",
            "2026-06-09T03:22:06.764181066+00:00",
            "foo:bar",
        ] {
            assert!(
                !needs_quoting(input),
                "bare colon should not force quoting: {:?}",
                input
            );
        }
    }

    #[test]
    fn quote_when_contains_hash() {
        for input in ["name with #hash", "a # b"] {
            assert!(needs_quoting(input), "input: {:?}", input);
        }
    }

    #[test]
    fn plain_scalar_passes_through_double_quote() {
        // YAML plain scalars allow embedded `"` (the only indicator that
        // must not appear at the start). We pass through unchanged; the
        // resulting plain scalar is still valid YAML and round-trips.
        let input = r#"has "quote""#;
        assert!(!needs_quoting(input));
        assert_eq!(yaml_quote_scalar(input), input);
    }

    #[test]
    fn plain_scalar_passes_through_backslash() {
        // YAML plain scalars allow `\` as a literal character. We pass
        // through unchanged.
        let input = r"has \ slash";
        assert!(!needs_quoting(input));
        assert_eq!(yaml_quote_scalar(input), input);
    }

    #[test]
    fn quote_when_contains_newline() {
        assert_eq!(yaml_quote_scalar("line1\nline2"), "\"line1\\nline2\"");
    }

    #[test]
    fn quote_when_contains_tab_or_carriage_return() {
        assert_eq!(yaml_quote_scalar("tab\there"), "\"tab\\there\"");
        assert_eq!(yaml_quote_scalar("cr\rhere"), "\"cr\\rhere\"");
    }

    #[test]
    fn quote_when_looks_like_bool_or_null() {
        for input in ["true", "false", "True", "FALSE", "null", "Null", "~"] {
            assert!(needs_quoting(input), "input: {:?}", input);
        }
    }

    #[test]
    fn quote_when_looks_like_number() {
        for input in ["0", "42", "-1.5", "1e10", "+0", "0.0", "100"] {
            assert!(needs_quoting(input), "input: {:?}", input);
        }
    }

    #[test]
    fn quote_when_leading_or_trailing_whitespace() {
        assert!(needs_quoting(" leading"));
        assert!(needs_quoting("trailing "));
    }

    #[test]
    fn quote_round_trip_through_yaml() {
        // The safety contract: every quoted form must round-trip through
        // serde_yaml and produce a string equal to the input.
        let cases = [
            "",
            "simple",
            "Test workflow with: colons and \"quotes\"",
            "name with #hash",
            "line1\nline2",
            "tab\there",
            "cr\rhere",
            "unicode: 名前",
            "starts with - dash",
            "starts with ? question",
            "starts with : colon",
            "starts with [ bracket",
            "starts with & ampersand",
            "true",
            "42",
            "0.0",
            "2026-06-09T03:22:06.764181066+00:00",
        ];
        for input in cases {
            let quoted = yaml_quote_scalar(input);
            let parsed: serde_yaml::Value =
                serde_yaml::from_str(&quoted).expect("quoted output must parse");
            let got = parsed.as_str().expect("must be a string");
            assert_eq!(got, input, "round-trip failed for {:?}", input);
        }
    }

    #[test]
    fn plain_scalars_still_parse_correctly() {
        // Plain-scalar inputs must still be valid YAML.
        let cases = [
            "my-flow",
            "code-assist",
            "A simple two-hat linear workflow for learning and small tasks",
        ];
        for input in cases {
            let quoted = yaml_quote_scalar(input);
            let parsed: serde_yaml::Value =
                serde_yaml::from_str(&quoted).expect("plain-scalar output must parse");
            assert_eq!(parsed.as_str(), Some(input));
        }
    }

    #[test]
    fn double_quoted_helper_handles_backslash_and_quote() {
        // Direct test of the escape table.
        assert_eq!(quote_as_double_quoted("a\\b"), "\"a\\\\b\"");
        assert_eq!(quote_as_double_quoted("a\"b"), "\"a\\\"b\"");
        assert_eq!(quote_as_double_quoted("a\nb"), "\"a\\nb\"");
    }
}

/// Loads preset templates from embedded file content.
///
/// Template files are embedded at compile time via `include_str!`.
pub struct TemplateCatalog;

impl TemplateCatalog {
    /// Get the list of available template names.
    pub fn template_names() -> Vec<&'static str> {
        vec![
            "minimal-linear",
            "code-assist",
            "debug",
            "research",
            "review",
            "ce-executor-lite",
        ]
    }

    /// Get a template manifest by name.
    ///
    /// Returns `None` if the template doesn't exist.
    pub fn get_manifest(name: &str) -> Option<TemplateManifest> {
        match name {
            "minimal-linear" => Some(TemplateManifest {
                name: "minimal-linear".to_string(),
                version: "1.0.0".to_string(),
                description: "A simple two-hat linear workflow for learning and small tasks".to_string(),
                category: "development".to_string(),
                difficulty: TemplateDifficulty::Beginner,
                source: None,
                recommended_checks: CheckProfile::Authoring,
                placeholders: vec![
                    TemplatePlaceholder {
                        name: "preset_name".to_string(),
                        description: "Name of the generated preset".to_string(),
                        default: None,
                    },
                    TemplatePlaceholder {
                        name: "description".to_string(),
                        description: "Description of the preset".to_string(),
                        default: None,
                    },
                    TemplatePlaceholder {
                        name: "generated_at".to_string(),
                        description: "RFC3339 timestamp of generation".to_string(),
                        default: None,
                    },
                ],
                output_notes: Some("Creates a minimal two-hat workflow: Planner → Executor".to_string()),
            }),
            "code-assist" => Some(TemplateManifest {
                name: "code-assist".to_string(),
                version: "1.0.0".to_string(),
                description: "Flexible implementation workflow following TDD principles".to_string(),
                category: "development".to_string(),
                difficulty: TemplateDifficulty::Intermediate,
                source: Some("builtin:code-assist".to_string()),
                recommended_checks: CheckProfile::Strict,
                placeholders: vec![
                    TemplatePlaceholder {
                        name: "preset_name".to_string(),
                        description: "Name of the generated preset".to_string(),
                        default: None,
                    },
                    TemplatePlaceholder {
                        name: "description".to_string(),
                        description: "Description of the preset".to_string(),
                        default: None,
                    },
                    TemplatePlaceholder {
                        name: "generated_at".to_string(),
                        description: "RFC3339 timestamp of generation".to_string(),
                        default: None,
                    },
                ],
                output_notes: Some("Based on builtin:code-assist. Four hats: Planner, Builder, Critic, Finalizer".to_string()),
            }),
            "debug" => Some(TemplateManifest {
                name: "debug".to_string(),
                version: "1.0.0".to_string(),
                description: "Bug investigation and root cause analysis following scientific method".to_string(),
                category: "debugging".to_string(),
                difficulty: TemplateDifficulty::Intermediate,
                source: Some("builtin:debug".to_string()),
                recommended_checks: CheckProfile::Authoring,
                placeholders: vec![
                    TemplatePlaceholder {
                        name: "preset_name".to_string(),
                        description: "Name of the generated preset".to_string(),
                        default: None,
                    },
                    TemplatePlaceholder {
                        name: "description".to_string(),
                        description: "Description of the preset".to_string(),
                        default: None,
                    },
                    TemplatePlaceholder {
                        name: "generated_at".to_string(),
                        description: "RFC3339 timestamp of generation".to_string(),
                        default: None,
                    },
                ],
                output_notes: Some("Based on builtin:debug. Four hats: Investigator, Tester, Fixer, Verifier".to_string()),
            }),
            "research" => Some(TemplateManifest {
                name: "research".to_string(),
                version: "1.0.0".to_string(),
                description: "Deep exploration for codebase analysis without code changes".to_string(),
                category: "research".to_string(),
                difficulty: TemplateDifficulty::Beginner,
                source: Some("builtin:research".to_string()),
                recommended_checks: CheckProfile::Authoring,
                placeholders: vec![
                    TemplatePlaceholder {
                        name: "preset_name".to_string(),
                        description: "Name of the generated preset".to_string(),
                        default: None,
                    },
                    TemplatePlaceholder {
                        name: "description".to_string(),
                        description: "Description of the preset".to_string(),
                        default: None,
                    },
                    TemplatePlaceholder {
                        name: "generated_at".to_string(),
                        description: "RFC3339 timestamp of generation".to_string(),
                        default: None,
                    },
                ],
                output_notes: Some("Based on builtin:research. Two hats: Researcher, Synthesizer. NO code changes.".to_string()),
            }),
            "review" => Some(TemplateManifest {
                name: "review".to_string(),
                version: "1.0.0".to_string(),
                description: "Code review without making modifications".to_string(),
                category: "review".to_string(),
                difficulty: TemplateDifficulty::Intermediate,
                source: Some("builtin:review".to_string()),
                recommended_checks: CheckProfile::Strict,
                placeholders: vec![
                    TemplatePlaceholder {
                        name: "preset_name".to_string(),
                        description: "Name of the generated preset".to_string(),
                        default: None,
                    },
                    TemplatePlaceholder {
                        name: "description".to_string(),
                        description: "Description of the preset".to_string(),
                        default: None,
                    },
                    TemplatePlaceholder {
                        name: "generated_at".to_string(),
                        description: "RFC3339 timestamp of generation".to_string(),
                        default: None,
                    },
                ],
                output_notes: Some("Based on builtin:review. Three hats: Reviewer, Analyzer, Closer. NO code changes.".to_string()),
            }),
            "ce-executor-lite" => Some(TemplateManifest {
                name: "ce-executor-lite".to_string(),
                version: "1.0.0".to_string(),
                description: "Simplified plan-driven execution without wave review".to_string(),
                category: "development".to_string(),
                difficulty: TemplateDifficulty::Advanced,
                source: Some("builtin:ce-executor".to_string()),
                recommended_checks: CheckProfile::Strict,
                placeholders: vec![
                    TemplatePlaceholder {
                        name: "preset_name".to_string(),
                        description: "Name of the generated preset".to_string(),
                        default: None,
                    },
                    TemplatePlaceholder {
                        name: "description".to_string(),
                        description: "Description of the preset".to_string(),
                        default: None,
                    },
                    TemplatePlaceholder {
                        name: "generated_at".to_string(),
                        description: "RFC3339 timestamp of generation".to_string(),
                        default: None,
                    },
                ],
                output_notes: Some("Simplified ce-executor. Two hats: Coordinator, Executor. No wave review.".to_string()),
            }),
            _ => None,
        }
    }

    /// Return the raw, unrendered template body for a given template name.
    ///
    /// Returns `None` if the template name is not in the catalog. This is
    /// the single source of truth for the `include_str!` paths so callers
    /// (the `show` command, the renderer, and any future template consumers)
    /// all read from the same path table — adding a new template requires
    /// updating exactly one match arm.
    pub fn raw_template(name: &str) -> Option<&'static str> {
        let body: &'static str = match name {
            "minimal-linear" => include_str!("../preset-templates/minimal-linear.yml"),
            "code-assist" => include_str!("../preset-templates/code-assist.yml"),
            "debug" => include_str!("../preset-templates/debug.yml"),
            "research" => include_str!("../preset-templates/research.yml"),
            "review" => include_str!("../preset-templates/review.yml"),
            "ce-executor-lite" => include_str!("../preset-templates/ce-executor-lite.yml"),
            _ => return None,
        };
        Some(body)
    }

    /// Render a template with the given values.
    ///
    /// Returns the rendered YAML content, or an error if rendering fails.
    pub fn render_template(name: &str, values: &[(&str, &str)]) -> Result<String, RenderError> {
        let template_content =
            Self::raw_template(name).ok_or_else(|| RenderError::InvalidYaml {
                source: format!("unknown template: {}", name),
            })?;

        TemplateRenderer::render(template_content, values)
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    // ── Version parsing ──────────────────────────────────────────────────────

    #[test]
    fn version_parse_simple() {
        let v = Version::parse("1.2.3").unwrap();
        assert_eq!(v.major, 1);
        assert_eq!(v.minor, 2);
        assert_eq!(v.patch, 3);
        assert!(v.prerelease.is_none());
        assert!(v.build.is_none());
    }

    #[test]
    fn version_parse_with_prerelease() {
        let v = Version::parse("1.0.0-alpha").unwrap();
        assert_eq!(v.major, 1);
        assert_eq!(v.prerelease, Some("alpha".to_string()));
    }

    #[test]
    fn version_parse_with_build_metadata() {
        let v = Version::parse("1.0.0+build.123").unwrap();
        assert_eq!(v.build, Some("build.123".to_string()));
    }

    #[test]
    fn version_parse_with_prerelease_and_build() {
        let v = Version::parse("1.0.0-alpha+001").unwrap();
        assert_eq!(v.prerelease, Some("alpha".to_string()));
        assert_eq!(v.build, Some("001".to_string()));
    }

    #[test]
    fn version_parse_zero() {
        let v = Version::parse("0.0.0").unwrap();
        assert_eq!(v.major, 0);
        assert_eq!(v.minor, 0);
        assert_eq!(v.patch, 0);
    }

    #[test]
    fn version_parse_large_numbers() {
        let v = Version::parse("999.888.777").unwrap();
        assert_eq!(v.major, 999);
        assert_eq!(v.minor, 888);
        assert_eq!(v.patch, 777);
    }

    #[test]
    fn version_parse_prerelease_multiple_identifiers() {
        let v = Version::parse("1.0.0-alpha.1.beta.2").unwrap();
        assert_eq!(v.prerelease, Some("alpha.1.beta.2".to_string()));
    }

    #[test]
    fn version_error_too_few_components() {
        let err = Version::parse("1.2").unwrap_err();
        assert!(matches!(err, VersionError::InvalidFormat { .. }));
    }

    #[test]
    fn version_error_too_many_components() {
        let err = Version::parse("1.2.3.4").unwrap_err();
        assert!(matches!(err, VersionError::InvalidFormat { .. }));
    }

    #[test]
    fn version_error_non_numeric() {
        let err = Version::parse("1.a.3").unwrap_err();
        assert!(matches!(err, VersionError::NonNumericComponent { .. }));
    }

    #[test]
    fn version_error_leading_zero() {
        let err = Version::parse("1.02.3").unwrap_err();
        assert!(matches!(err, VersionError::LeadingZero { .. }));
    }

    #[test]
    fn version_error_leading_zero_patch() {
        let err = Version::parse("1.2.03").unwrap_err();
        assert!(matches!(err, VersionError::LeadingZero { .. }));
    }

    #[test]
    fn version_error_empty_prerelease() {
        let err = Version::parse("1.0.0-").unwrap_err();
        assert!(matches!(err, VersionError::EmptyPrerelease));
    }

    #[test]
    fn version_error_empty_prerelease_identifier() {
        let err = Version::parse("1.0.0-alpha..1").unwrap_err();
        assert!(matches!(err, VersionError::EmptyPrereleaseIdentifier));
    }

    #[test]
    fn version_error_invalid_prerelease_char() {
        let err = Version::parse("1.0.0-alpha_beta").unwrap_err();
        assert!(matches!(
            err,
            VersionError::InvalidPrereleaseCharacter { character: '_', .. }
        ));
    }

    #[test]
    fn version_error_empty_build_metadata() {
        let err = Version::parse("1.0.0+").unwrap_err();
        assert!(matches!(err, VersionError::EmptyBuildMetadata));
    }

    #[test]
    fn version_error_empty_component() {
        let err = Version::parse("1..3").unwrap_err();
        assert!(matches!(err, VersionError::InvalidFormat { .. }));
    }

    // ── Version ordering ─────────────────────────────────────────────────────

    #[test]
    fn version_order_major() {
        let v1 = Version::parse("1.0.0").unwrap();
        let v2 = Version::parse("2.0.0").unwrap();
        assert!(v1 < v2);
    }

    #[test]
    fn version_order_minor() {
        let v1 = Version::parse("1.0.0").unwrap();
        let v2 = Version::parse("1.1.0").unwrap();
        assert!(v1 < v2);
    }

    #[test]
    fn version_order_patch() {
        let v1 = Version::parse("1.0.0").unwrap();
        let v2 = Version::parse("1.0.1").unwrap();
        assert!(v1 < v2);
    }

    #[test]
    fn version_order_prerelease_lower() {
        // Release version is greater than any prerelease with same major.minor.patch
        let release = Version::parse("1.0.0").unwrap();
        let pre = Version::parse("1.0.0-alpha").unwrap();
        assert!(pre < release);
    }

    #[test]
    fn version_order_prerelease_alpha() {
        let a = Version::parse("1.0.0-alpha").unwrap();
        let b = Version::parse("1.0.0-beta").unwrap();
        // ASCII order: alpha < beta
        assert!(a < b);
    }

    #[test]
    fn version_order_prerelease_dotted() {
        let a = Version::parse("1.0.0-alpha.1").unwrap();
        let b = Version::parse("1.0.0-alpha.2").unwrap();
        assert!(a < b);
    }

    #[test]
    fn version_order_prerelease_longer_prerelease_wins() {
        let a = Version::parse("1.0.0-alpha").unwrap();
        let b = Version::parse("1.0.0-alpha.1").unwrap();
        // "alpha" < "alpha.1" per SemVer: identifiers are compared as raw ASCII
        assert!(a < b);
    }

    // ── Version display ─────────────────────────────────────────────────────

    #[test]
    fn version_display_roundtrips() {
        let cases = [
            "1.0.0",
            "0.0.1",
            "1.2.3-alpha",
            "1.2.3-alpha.1",
            "1.2.3+build",
            "1.2.3-alpha+build",
            "1.2.3-alpha.1+build.123",
        ];

        for case in cases {
            let v = Version::parse(case).unwrap();
            assert_eq!(v.to_string(), case, "roundtrip failed for '{}'", case);
        }
    }

    // ── Version compatibility ─────────────────────────────────────────────────

    #[test]
    fn version_is_compatible_with_exact() {
        let a = Version::parse("1.2.3").unwrap();
        let b = Version::parse("1.2.3").unwrap();
        assert!(a.is_compatible_with(&b));
    }

    #[test]
    fn version_is_compatible_with_patch_higher() {
        let a = Version::parse("1.2.3").unwrap();
        let b = Version::parse("1.2.5").unwrap();
        assert!(a.is_compatible_with(&b));
    }

    #[test]
    fn version_is_compatible_with_minor_higher() {
        let a = Version::parse("1.2.3").unwrap();
        let b = Version::parse("1.3.0").unwrap();
        assert!(a.is_compatible_with(&b));
    }

    #[test]
    fn version_is_not_compatible_with_major_higher() {
        let a = Version::parse("1.2.3").unwrap();
        let b = Version::parse("2.0.0").unwrap();
        assert!(!a.is_compatible_with(&b));
    }

    #[test]
    fn version_is_not_compatible_with_minor_lower() {
        let a = Version::parse("1.2.3").unwrap();
        let b = Version::parse("1.1.0").unwrap();
        assert!(!a.is_compatible_with(&b));
    }

    #[test]
    fn version_is_not_compatible_with_patch_lower() {
        let a = Version::parse("1.2.3").unwrap();
        let b = Version::parse("1.2.2").unwrap();
        assert!(!a.is_compatible_with(&b));
    }

    // ── XPresetMetadata parsing ─────────────────────────────────────────────

    const MINIMAL_XPRESET_YAML: &str = r#"
x_preset:
  schema_version: 1
  template: minimal-linear
  template_version: "1.0.0"
  generated_by: "ralph preset new"
  generated_at: "2026-06-05T00:00:00Z"
  name: my-flow
  description: "My workflow"
"#;

    #[test]
    fn xpreset_parse_minimal() {
        let value: serde_yaml::Value = serde_yaml::from_str(MINIMAL_XPRESET_YAML).unwrap();
        let metadata = XPresetMetadata::from_yaml_value(&value)
            .unwrap()
            .expect("x_preset should be present");
        assert_eq!(metadata.schema_version, 1);
        assert_eq!(metadata.template, "minimal-linear");
        assert_eq!(metadata.template_version, "1.0.0");
        assert_eq!(metadata.name, "my-flow");
        assert_eq!(metadata.description, "My workflow");
        assert_eq!(metadata.check_profile, CheckProfile::Authoring); // default
    }

    #[test]
    fn xpreset_parse_with_all_fields() {
        let yaml = r#"
x_preset:
  schema_version: 1
  template: code-assist
  template_version: "1.2.0"
  generated_by: "ralph preset new"
  generated_at: "2026-06-05T12:00:00Z"
  name: team-flow
  description: "Team code assist workflow"
  check_profile: strict
  ralph_compat: ">=0.2.0"
"#;
        let value: serde_yaml::Value = serde_yaml::from_str(yaml).unwrap();
        let metadata = XPresetMetadata::from_yaml_value(&value)
            .unwrap()
            .expect("x_preset should be present");
        assert_eq!(metadata.check_profile, CheckProfile::Strict);
        assert_eq!(metadata.ralph_compat, Some(">=0.2.0".to_string()));
    }

    #[test]
    fn xpreset_parse_missing_x_preset() {
        let yaml = "hats:\n  a:\n    name: A";
        let value: serde_yaml::Value = serde_yaml::from_str(yaml).unwrap();
        let result = XPresetMetadata::from_yaml_value(&value).unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn xpreset_parse_unsupported_schema_version() {
        let yaml = r#"
x_preset:
  schema_version: 99
  template: test
  template_version: "1.0.0"
  generated_by: "ralph preset new"
  generated_at: "2026-06-05T00:00:00Z"
  name: test
  description: test
"#;
        let value: serde_yaml::Value = serde_yaml::from_str(yaml).unwrap();
        let err = XPresetMetadata::from_yaml_value(&value).unwrap_err();
        assert!(matches!(
            err,
            XPresetParseError::UnsupportedSchemaVersion {
                found: 99,
                supported: 1
            }
        ));
    }

    #[test]
    fn xpreset_parse_invalid_template_version() {
        let yaml = r#"
x_preset:
  schema_version: 1
  template: test
  template_version: "not-a-version"
  generated_by: "ralph preset new"
  generated_at: "2026-06-05T00:00:00Z"
  name: test
  description: test
"#;
        let value: serde_yaml::Value = serde_yaml::from_str(yaml).unwrap();
        let err = XPresetMetadata::from_yaml_value(&value).unwrap_err();
        assert!(matches!(
            err,
            XPresetParseError::InvalidTemplateVersion { .. }
        ));
    }

    #[test]
    fn xpreset_is_generated() {
        let yaml = r#"
x_preset:
  schema_version: 1
  template: test
  template_version: "1.0.0"
  generated_by: "ralph preset new --check"
  generated_at: "2026-06-05T00:00:00Z"
  name: test
  description: test
"#;
        let value: serde_yaml::Value = serde_yaml::from_str(yaml).unwrap();
        let metadata = XPresetMetadata::from_yaml_value(&value)
            .unwrap()
            .expect("x_preset should be present");
        assert!(metadata.is_generated());
    }

    // ── CheckProfile ─────────────────────────────────────────────────────────

    #[test]
    fn check_profile_default_is_authoring() {
        assert_eq!(CheckProfile::default(), CheckProfile::Authoring);
    }

    #[test]
    fn check_profile_display() {
        assert_eq!(CheckProfile::Authoring.to_string(), "authoring");
        assert_eq!(CheckProfile::Strict.to_string(), "strict");
        assert_eq!(CheckProfile::RuntimeReady.to_string(), "runtime-ready");
    }

    // ── TemplateManifest ─────────────────────────────────────────────────────

    #[test]
    fn template_manifest_is_beginner_friendly() {
        let manifest = TemplateManifest {
            name: "test".to_string(),
            version: "1.0.0".to_string(),
            description: "Test template".to_string(),
            category: "development".to_string(),
            difficulty: TemplateDifficulty::Beginner,
            source: None,
            recommended_checks: CheckProfile::Authoring,
            placeholders: vec![],
            output_notes: None,
        };
        assert!(manifest.is_beginner_friendly());
    }

    #[test]
    fn template_manifest_required_placeholders() {
        let manifest = TemplateManifest {
            name: "test".to_string(),
            version: "1.0.0".to_string(),
            description: "Test template".to_string(),
            category: "development".to_string(),
            difficulty: TemplateDifficulty::Beginner,
            source: None,
            recommended_checks: CheckProfile::Authoring,
            placeholders: vec![
                TemplatePlaceholder {
                    name: "preset_name".to_string(),
                    description: "Name of the preset".to_string(),
                    default: None,
                },
                TemplatePlaceholder {
                    name: "author".to_string(),
                    description: "Author name".to_string(),
                    default: Some("Anonymous".to_string()),
                },
            ],
            output_notes: None,
        };

        let required = manifest.required_placeholders();
        assert_eq!(required, vec!["preset_name"]);
    }

    // ── TemplateRenderer tests ──────────────────────────────────────────────

    #[test]
    fn renderer_basic_substitution() {
        let template = "name: {{preset_name}}";
        let result = TemplateRenderer::render(template, &[("preset_name", "my-flow")]).unwrap();
        assert_eq!(result, "name: my-flow");
    }

    #[test]
    fn renderer_multiple_placeholders() {
        let template = "name: {{preset_name}}\ndesc: {{description}}";
        let result = TemplateRenderer::render(
            template,
            &[
                ("preset_name", "my-flow"),
                ("description", "A test workflow"),
            ],
        )
        .unwrap();
        assert_eq!(result, "name: my-flow\ndesc: A test workflow");
    }

    #[test]
    fn renderer_preserves_non_placeholder_content() {
        let template = "# Header\nname: {{preset_name}}\n# Footer";
        let result = TemplateRenderer::render(template, &[("preset_name", "my-flow")]).unwrap();
        assert_eq!(result, "# Header\nname: my-flow\n# Footer");
    }

    #[test]
    fn renderer_unknown_placeholder_rejected() {
        let template = "evil: {{shell_exec}}";
        let err = TemplateRenderer::render(template, &[("shell_exec", "rm -rf /")]).unwrap_err();
        assert!(matches!(err, RenderError::UnknownPlaceholder { name } if name == "shell_exec"));
    }

    #[test]
    fn renderer_missing_required_value() {
        let template = "name: {{preset_name}}";
        // No values provided at all
        let err = TemplateRenderer::render(template, &[]).unwrap_err();
        assert!(
            matches!(err, RenderError::MissingPlaceholderValue { name } if name == "preset_name")
        );
    }

    #[test]
    fn renderer_validate_placeholders_valid() {
        let template = "name: {{preset_name}}\ndesc: {{description}}";
        assert!(TemplateRenderer::validate_placeholders(template).is_ok());
    }

    #[test]
    fn renderer_validate_placeholders_unknown() {
        let template = "evil: {{shell_exec}}";
        let err = TemplateRenderer::validate_placeholders(template).unwrap_err();
        assert!(matches!(err, RenderError::UnknownPlaceholder { .. }));
    }

    // ── TemplateCatalog tests ───────────────────────────────────────────────

    #[test]
    fn catalog_template_names() {
        let names = TemplateCatalog::template_names();
        assert!(names.contains(&"minimal-linear"));
        assert!(names.contains(&"code-assist"));
        assert!(names.contains(&"debug"));
        assert!(names.contains(&"research"));
        assert!(names.contains(&"review"));
        assert!(names.contains(&"ce-executor-lite"));
        assert_eq!(names.len(), 6);
    }

    #[test]
    fn catalog_get_manifest_known() {
        let manifest = TemplateCatalog::get_manifest("minimal-linear").expect("should exist");
        assert_eq!(manifest.name, "minimal-linear");
        assert_eq!(manifest.version, "1.0.0");
        assert_eq!(manifest.difficulty, TemplateDifficulty::Beginner);
    }

    #[test]
    fn catalog_get_manifest_unknown() {
        assert!(TemplateCatalog::get_manifest("nonexistent").is_none());
    }

    #[test]
    fn catalog_render_minimal_linear() {
        let result = TemplateCatalog::render_template(
            "minimal-linear",
            &[
                ("preset_name", "my-test-flow"),
                ("description", "My test workflow"),
                ("generated_at", "2026-06-08T00:00:00Z"),
            ],
        )
        .unwrap();

        // Verify placeholder substitution
        assert!(result.contains("name: my-test-flow"));
        assert!(result.contains("description: My test workflow"));
        assert!(result.contains("generated_at: 2026-06-08T00:00:00Z"));

        // Verify no leftover placeholders
        assert!(!result.contains("{{preset_name}}"));
        assert!(!result.contains("{{description}}"));
        assert!(!result.contains("{{generated_at}}"));

        // Verify it's valid YAML
        assert!(serde_yaml::from_str::<serde_yaml::Value>(&result).is_ok());
    }

    #[test]
    fn catalog_render_code_assist() {
        let result = TemplateCatalog::render_template(
            "code-assist",
            &[
                ("preset_name", "team-code"),
                ("description", "Team code assist workflow"),
                ("generated_at", "2026-06-08T00:00:00Z"),
            ],
        )
        .unwrap();

        assert!(result.contains("name: team-code"));
        assert!(result.contains("description: Team code assist workflow"));
        assert!(!result.contains("{{preset_name}}"));
        assert!(serde_yaml::from_str::<serde_yaml::Value>(&result).is_ok());
    }

    #[test]
    fn catalog_render_unknown_template() {
        let err = TemplateCatalog::render_template("nonexistent", &[("preset_name", "test")])
            .unwrap_err();
        assert!(matches!(err, RenderError::InvalidYaml { .. }));
    }

    #[test]
    fn catalog_render_missing_required_placeholder() {
        // minimal-linear requires preset_name, description, and generated_at
        let err = TemplateCatalog::render_template(
            "minimal-linear",
            &[("preset_name", "only-one")], // missing description and generated_at
        )
        .unwrap_err();
        assert!(matches!(err, RenderError::MissingPlaceholderValue { .. }));
    }
}
